export const C = {
  bg:'#f0f4ff',surf:'#ffffff',surfAlt:'#f8faff',
  navy:'#0a2463',navyM:'#1a3a7a',
  blue:'#1e90ff',blueL:'#e8f4ff',blueM:'#4dabf7',
  green:'#2d9e6b',greenL:'#e8f8f0',
  amber:'#e67e22',amberL:'#fef5e7',
  red:'#c0392b',redL:'#fef0ef',
  text:'#0a1628',textM:'#3a4a6b',textS:'#6b7fa3',
  border:'#dde4f5',
  sh:'0 1px 4px rgba(10,36,99,.07),0 4px 16px rgba(10,36,99,.04)',
  shM:'0 4px 24px rgba(10,36,99,.13)',
}

export const LEVELS = ['A1','A2','B1','B2']

export const CURRICULUM = {
  A1:[
    {id:'a1-1',title:'Phonetics & Basics',icon:'🔤',desc:'Alphabet, Umlauts, pronunciation rules',
     flow:`1. Introduction to German as a phonetic language.\n2. All German Alphabets, their pronunciation and comparison to English.\n3. Vowel sounds: A, E, I, O, U (long vs short).\n4. The Umlauts: ä, ö, ü — visual tongue positioning.\n5. The 'ß' (Eszett) — history and modern usage.\n6. Diphthongs ei, ie, eu, au pronunciation drills.\n7. Consonant clusters: sch, st, sp, ch (Ich-laut vs Ach-laut).\n8. The German uvular friction, 'W' sound (as English V), and 'V' sound (as English F).`},
    {id:'a1-2',title:'Greetings & Introductions',icon:'👋',desc:'Formal/informal greetings, saying your name',
     flow:`1. Formal greetings: Guten Morgen, Guten Tag, Guten Abend.\n2. Informal greetings: Hallo, Hi, Moin.\n3. 'Wie geht es Ihnen?' vs 'Wie geht's?' and answering (Gut, sehr gut, es geht).\n4. Introducing yourself: 'Ich heiße...', 'Mein Name ist...'.\n5. Asking names: 'Wie heißen Sie?' / 'Wer bist du?'.\n6. Origins: 'Woher kommen Sie?' / 'Ich komme aus...'.\n7. Farewell expressions: Auf Wiedersehen vs. Tschüss.\n8. Handshake culture in Germany. Pronunciation drill: 'Herzlich Willkommen'.`},
    {id:'a1-3',title:"The Verb 'To Be' (sein)",icon:'📗',desc:'Conjugation of sein, personal pronouns',
     flow:`1. Subject pronouns: ich, du, er, sie, es, wir, ihr, sie, Sie.\n2. Conjugation of sein: bin, bist, ist, sind, seid, sind.\n3. Using 'sein' for identity ('Ich bin Krankenschwester') and adjectives ('Das ist schön').\n4. Forming questions by flipping Subject-Verb position.\n5. Negation with nicht: 'Ich bin nicht müde'.\n6. Formal 'Sie' vs. plural 'sie' — common errors and how to avoid them.\n7. Hospital application: introducing yourself as a nurse to patients.`},
    {id:'a1-4',title:'Numbers & Data',icon:'🔢',desc:'Counting 1–100, phone numbers, age, calendar',
     flow:`1. 0–12: The irregular foundations.\n2. 13–19: The '-zehn' suffix; 20–90: The '-zig' suffix.\n3. The 'reversed' rule: 'One-and-twenty' (einundzwanzig).\n4. 100 (hundert) and 1000 (tausend).\n5. Speaking phone numbers and email address pronunciation ('punkt', 'at', 'unterstrich').\n6. Asking and answering age: 'Wie alt sind Sie?' / 'Ich bin... Jahre alt'.\n7. Days of the week (Montag–Sonntag) and Months of the year.\n8. Hospital use: reading patient room numbers, dates of birth, appointment times.`},
    {id:'a1-5',title:'Nouns & Genders',icon:'📖',desc:'Der/Die/Das, gender rules, plurals',
     flow:`1. Every noun has a gender (M/F/N) — explanation of the noun gender concept.\n2. Types of verbs overview.\n3. Der: Masculine signals; Die: Feminine signals; Das: Neuter signals.\n4. Definite articles (der/die/das) vs Indefinite articles (ein/eine/ein).\n5. The plural article is always 'die' with common plural endings (-en, -er, -e, -s).\n6. Categorizing objects in a hospital room with correct articles.\n7. Memory tips for gender recognition.`},
    {id:'a1-6',title:'Verbs in Present Tense',icon:'⚡',desc:'Regular verb conjugation, haben',
     flow:`1. The 'Stem + Ending' system.\n2. Endings: -e, -st, -t, -en, -t, -en for ich/du/er/wir/ihr/sie.\n3. Verbs: wohnen, kommen, lernen, machen.\n4. Stem changes with -t/-d endings (e.g., arbeiten → ich arbeite).\n5. Introduction to irregular 'haben' present conjugation.\n6. Language elements: identifying verbs, subjects, and objects.\n7. Hospital sentences: 'Ich arbeite im Krankenhaus', 'Die Ärztin kommt'.`},
    {id:'a1-7',title:'Sentence Structure',icon:'💬',desc:'S-V-O, questions, word order rules',
     flow:`1. Word order in basic statements (Aussagesätze) — Verb always in Position 2.\n2. Forming basic yes/no questions (V-S-O): Ja/Nein Fragen.\n3. W-Questions: Was, Wo, Wer, Wann, Woher (Position 1, Verb in Position 2).\n4. Cultural note: Directness in German questions.\n5. Inversion with time/place: 'Heute arbeite ich auf Station 3'.\n6. Practicing hospital-context sentences with correct word order.`},
    {id:'a1-8',title:'Family & Relations',icon:'👨‍👩‍👧',desc:'Family vocabulary, all possessives, Imperativ',
     flow:`1. Vocab: Vater, Mutter, Bruder, Schwester, Großeltern, Kinder.\n2. ALL possessive pronouns/articles: mein/meine, dein/deine, sein/seine, ihr/ihre, unser/unsere, euer/eure, ihr/ihre — all forms and cases covered.\n3. Asking 'Who is that?': 'Wer ist das?'.\n4. Describing marital status (ledig, verheiratet, geschieden) and using 'haben' for siblings.\n5. Genitive 's (Sarahs Vater, Dr. Müllers Patient).\n6. Introduction to Imperativ form for basic instructions (Kommen Sie!, Bitte setzen Sie sich!).`},
    {id:'a1-9',title:'Accusative Case I',icon:'🎯',desc:"Direct objects, 'Haben', article changes",
     flow:`1. Concept of Subject (Nominative) vs Direct Object (Accusative).\n2. The ONLY change: 'Der' becomes 'Den' and 'Ein' becomes 'Einen'.\n3. Feminine (die/eine) and Neuter (das/ein) articles stay exactly the same.\n4. Verbs that trigger Accusative: haben, brauchen, suchen, möchten.\n5. Examples: 'Ich habe einen Patienten', 'Ich suche den Arzt'.\n6. Hospital drills: 'Ich brauche eine Spritze', 'Der Patient hat einen Termin'.`},
    {id:'a1-10',title:'Accusative Case II',icon:'🔀',desc:'Accusative pronouns and prepositions',
     flow:`1. Accusative personal pronouns: mich, dich, ihn, sie, es, uns, euch, sie, Sie.\n2. Substituting nouns with accusative pronouns (e.g., 'Ich suche ihn').\n3. All governing Accusative Prepositions: durch, für, gegen, ohne, um, bis, entlang.\n4. Sentence construction drills combining accusative verbs and prepositions.\n5. Hospital context: 'Das Medikament ist für den Patienten', 'Ohne eine Überweisung geht es nicht'.`},
    {id:'a1-11',title:'Home & Living',icon:'🏠',desc:'Rooms, furniture, apartment vocabulary',
     flow:`1. Rooms: Küche, Bad, Wohnzimmer, Schlafzimmer, Flur, Balkon.\n2. Furniture: Bett, Tisch, Stuhl, Schrank, Sofa, Regal.\n3. Adjectives: groß, klein, hell, dunkel, teuer, gemütlich.\n4. Predicative adjectives: 'Das Zimmer ist schön'.\n5. Apartment types (WG, Wohnung, Haus) and renting terms (Miete, Nebenkosten, Kaution).\n6. Grammar: 'Es gibt...' + Accusative (There is / There are).\n7. Practical use for nurses: describing accommodation in Germany.`},
    {id:'a1-12',title:'Food & Groceries',icon:'🛒',desc:'Supermarket vocab, quantities, meal words',
     flow:`1. Breakfast, Lunch, Dinner vocabulary.\n2. Common foods: Brot, Käse, Obst, Fleisch, Gemüse; Drinks: Wasser, Kaffee, Bier, Wein, Saft.\n3. Buying units: Ein Kilo, eine Flasche, ein Glas, ein Paket, eine Dose.\n4. Irregular verb conjugation: 'essen' (du isst, er isst) and 'trinken'.\n5. Expressing hunger/thirst: Hunger/Durst haben.\n6. Hospital context: 'Was möchte der Patient essen?', dietary restrictions vocabulary.`},
    {id:'a1-13',title:'Negation',icon:'🚫',desc:"'Nicht' vs 'Kein' — when to use each",
     flow:`1. The structural difference: 'Nicht' vs 'Kein'.\n2. Using 'Kein' for nouns with indefinite articles or no articles.\n3. Using 'Nicht' for verbs, adjectives, pronouns, adverbs, and proper names.\n4. Position of 'nicht' in sentences.\n5. Negative questions and responding with 'Doch!'.\n6. Drills: 'Ich habe kein Fieber' vs 'Ich arbeite nicht heute'.\n7. Hospital use: 'Der Patient hat keine Allergien', 'Das Medikament wirkt nicht'.`},
    {id:'a1-14',title:'Time & Clock',icon:'🕐',desc:'Formal/informal time, clock vocabulary',
     flow:`1. Formal time (24h system) used in hospitals, transport, schedules.\n2. Informal conversational time: Viertel vor, Viertel nach, halb.\n3. Asking time: 'Wie spät ist es?' / 'Wie viel Uhr ist es?'.\n4. Prepositions 'um' for specific clock times and 'von... bis' (from... to).\n5. Asking about duration: 'Wie lange?'.\n6. Times of day: morgens, mittags, abends, nachts and hospital relevance.\n7. Cultural note on punctuality in German workplaces.\n8. Shift vocabulary: Frühschicht, Spätschicht, Nachtschicht.`},
    {id:'a1-15',title:'Daily Routine & Separable Verbs',icon:'📅',desc:'Separable verbs, daily schedule expressions',
     flow:`1. Introduction to separable verb prefixes: auf-, an-, ab-, ein-, fern-, vor-, zu-.\n2. Prefix behavior: moves to the very end of the main clause.\n3. Common verbs: aufstehen, anrufen, einkaufen, fernsehen, vorbereiten, abgeben.\n4. Conjugating the main verb stem correctly while prefix goes to end.\n5. Interaction with time expressions: 'Ich stehe um 6 Uhr auf'.\n6. Hospital daily routine: 'Ich fange um 7 Uhr an', 'Ich höre um 15 Uhr auf'.`},
    {id:'a1-16',title:'Modal Verbs I',icon:'🎛️',desc:'Können and Wollen — ability and intention',
     flow:`1. Concept: Expressing Ability (können) and Intention/Desire (wollen).\n2. Modal Verb sentence architecture: Modal verb at Position 2, Infinitive at the absolute end.\n3. Conjugation irregularities: ich and er/sie/es forms are identical (ich kann, er kann).\n4. Full conjugation tables for können and wollen.\n5. Examples: 'Ich kann Deutsch sprechen', 'Ich will Krankenschwester werden'.\n6. Hospital use: 'Können Sie bitte warten?', 'Ich will dem Patienten helfen'.`},
    {id:'a1-17',title:'Modal Verbs II',icon:'🎛️',desc:'Müssen, Dürfen, Sollen, Möchten',
     flow:`1. Expressing Obligation/Necessity (müssen) and Permission/Prohibition (dürfen).\n2. Introduction to sollen (should/expected to) and möchten (would like — polite want).\n3. Full conjugation tables and vowel mutations for all modals.\n4. Negating modals: 'Du darfst hier nicht parken', 'Du musst das nicht machen'.\n5. Distinguishing 'müssen nicht' (don't have to) vs 'nicht dürfen' (must not).\n6. Hospital critical usage: 'Sie müssen nüchtern bleiben', 'Sie dürfen nicht aufstehen', 'Möchten Sie Schmerzmittel?'.`},
    {id:'a1-18',title:'Sentence Architecture Masterclass',icon:'🏗️',desc:'Word order with modals, separable verbs, inversion',
     flow:`1. The 'Golden Rule': Finite verb always remains in Position 2.\n2. Inversion: Moving time or place phrases to Position 1, forcing subject to position 3.\n3. Separable verb bracket rule: prefix at end of clause.\n4. Modal verb bracket: infinitive at end of clause.\n5. Combining modals and separable verbs: 'Ich muss um 7 Uhr aufstehen'.\n6. Group drill: Transforming regular statements into modal and inverted sentences.\n7. Hospital complex sentences: 'Morgen muss ich früh anfangen'.`},
    {id:'a1-19',title:'Travel & Transport',icon:'🚂',desc:'Tickets, station vocab, directions, mit + Dativ',
     flow:`1. Modes of transport: Zug, Bus, Flugzeug, Fahrrad, U-Bahn, Straßenbahn.\n2. At the station: Gleis, Fahrkarte, Verspätung, Abfahrt, Ankunft.\n3. Introduction to Dativ then 'mit' + Dative: mit dem Zug, mit der U-Bahn, mit dem Bus.\n4. Directions: links, rechts, geradeaus, die erste Straße, die zweite Straße.\n5. Asking 'Wo ist der Bahnhof?', 'Wie komme ich zum Krankenhaus?'.\n6. Ticket buying phrases: 'Einmal nach München, bitte', 'Einfach oder hin und zurück?'.\n7. Practical navigation for nurses: getting to work, finding departments.`},
    {id:'a1-20',title:'The Past Tense (Perfekt) I',icon:'⏪',desc:"'Haben' + Partizip II for regular verbs",
     flow:`1. Spoken vs Written Past Tense concepts in German.\n2. Structural formula: Auxiliary verb 'haben' (Position 2) + Partizip II (absolute end).\n3. Constructing regular participles: ge + stem + t (gelernt, gekauft, gemacht, gearbeitet).\n4. Exception: Verbs ending in -ieren do not get 'ge-' prefix (studiert, operiert).\n5. Participles for separable verbs: prefix + ge + stem + t (eingekauft, aufgestanden).\n6. Hospital examples: 'Ich habe den Patienten versorgt', 'Die Ärztin hat das Rezept ausgestellt'.`},
    {id:'a1-21',title:'The Past Tense (Perfekt) II',icon:'⏮️',desc:"'Sein' + Partizip II for motion and change verbs",
     flow:`1. Rules for choosing the auxiliary verb: when to use 'sein' (verbs of motion or change of state).\n2. Key sein-verbs: gehen, kommen, fahren, fliegen, laufen, reisen.\n3. Change-of-state verbs with sein: einschlafen, aufwachen, werden, sterben, bleiben.\n4. Strong/irregular Partizip II forms: gegangen, gefahren, gekommen, geschlafen, getrunken, gesehen.\n5. Common exceptions using haben: gegessen, getrunken, gesehen, geschlafen.\n6. Präteritum introduction for haben (hatte) and sein (war) only.\n7. Hospital narrative: 'Die Patientin ist gestürzt', 'Der Arzt ist gekommen'.`},
    {id:'a1-22',title:'Coordinating Conjunctions',icon:'🔗',desc:'ADUSO connectors — aber, denn, und, sondern, oder',
     flow:`1. Introduction to ADUSO connectors: Aber, Denn, Und, Sondern, Oder.\n2. Syntax rule: ADUSO conjunctions occupy Position 0 and do NOT shift verb position.\n3. Distinction between 'aber' (but) and 'sondern' (but rather — after negation).\n4. Practical sentence connection drills.\n5. Hospital examples: 'Ich habe Schmerzen, aber ich kann arbeiten', 'Der Patient hat Fieber, denn er ist erkältet'.\n6. Building longer, more natural-sounding German sentences.`},
    {id:'a1-23',title:'Dative Case Intro',icon:'📥',desc:'Indirect objects, Dative article changes',
     flow:`1. Structural concept: Direct object recipient (Accusative) vs Indirect object recipient (Dative).\n2. Case alterations for definite articles: der/das → dem, die → der, Plural die → den (+ n added to noun).\n3. Indefinite article shifts: ein/ein → einem, eine → einer.\n4. High-frequency verbs requiring Dative objects: geben, helfen, danken, gehören, erklären, zeigen.\n5. Examples: 'Ich helfe der Patientin', 'Das Buch gehört dem Arzt'.\n6. Hospital use: 'Ich gebe dem Patienten das Medikament', 'Können Sie mir helfen?'.`},
    {id:'a1-24',title:'Dative Pronouns & Prepositions',icon:'📍',desc:'Dative pronouns, fixed Dative prepositions',
     flow:`1. Dative Personal Pronouns: mir, dir, ihm, ihr, ihm, uns, euch, ihnen, Ihnen.\n2. Contrasting: 'Ich sehe dich (Acc)' vs 'Ich helfe dir (Dat)'.\n3. Fixed Dative Prepositions: mit, zu, nach, bei, von, aus, seit, gegenüber.\n4. Contractions: zum (zu+dem), zur (zu+der), beim (bei+dem), vom (von+dem).\n5. Sentence formulation: 'Ich gehe zum Arzt', 'Seit einem Jahr lerne ich Deutsch'.\n6. Hospital key phrases: 'bei der Operation', 'nach der Visite', 'vom Dienst'.`},
    {id:'a1-25',title:'Two-Way Prepositions',icon:'↔️',desc:'Wechselpräpositionen — Accusative vs Dative',
     flow:`1. The 9 Two-Way Prepositions: in, an, auf, unter, über, vor, hinter, neben, zwischen.\n2. The Golden Rule: Wohin? (Where to? — movement) → triggers Accusative case.\n3. Wo? (Where? — location/position) → triggers Dative case.\n4. Contractions: im (in+dem), ins (in+das), am (an+dem), ans (an+das).\n5. Visualizing spatial concepts with hospital room furniture.\n6. Hospital examples: 'Das Medikament liegt auf dem Tisch (Dat)', 'Legen Sie es auf den Tisch (Acc)'.`},
    {id:'a1-26',title:'Body & Health',icon:'🏥',desc:'Anatomy, symptoms, pain descriptions',
     flow:`1. Anatomy terms: Kopf, Rücken, Arme, Beine, Bauch, Augen, Ohren, Nase, Mund, Herz, Lunge, Niere.\n2. Saying something hurts: 'Mein Kopf tut weh', 'Ich habe Schmerzen im Bauch'.\n3. Symptoms: Fieber, Husten, Schnupfen, Schwindel, Übelkeit, Erbrechen, Verstopfung, Durchfall.\n4. Describing pain quality: stark, leicht, dumpf, stechend, brennend, pochend.\n5. Apotheke vs. Arztpraxis vs. Krankenhaus — when to go where.\n6. Making appointments: 'Ich brauche einen Termin', 'Ich habe seit drei Tagen Fieber'.\n7. Vital signs vocabulary: Blutdruck, Puls, Temperatur, Atemfrequenz.`},
    {id:'a1-27',title:'Formal Writing',icon:'✉️',desc:'Email structure, letters, apologies, sick notes',
     flow:`1. Formal layout guidelines for standard German letters and emails.\n2. Formal Salutations: 'Sehr geehrte Damen und Herren', 'Sehr geehrter Herr Dr. Müller'.\n3. Informal equivalents: 'Liebe...' / 'Viele Grüße'.\n4. Formal Closings: 'Mit freundlichen Grüßen'.\n5. Structure: Betreff (subject), Anrede (salutation), Hauptteil (body), Schlussformel (closing).\n6. Key writing tasks: sick notes, inviting to an event, apologizing for absence, requesting information.\n7. Hospital written communication: nurse-to-nurse notes, simple patient appointment letters.`},
  ],
  A2:[
    {id:'a2-1',title:'A2 Transition & A1 Review',icon:'🔄',desc:'A1 recap, case tables, A2 objectives',
     flow:`1. Transition overview and setting A2 milestone expectations.\n2. Quick review of Nominative, Accusative, Dative article tables.\n3. Verb position rules recap: V2, inversion, modal + infinitive bracket.\n4. Review of separable verbs and Perfekt formation.\n5. Introduction to A2 learning objectives and Goethe A2 exam structure.\n6. Self-assessment: students identify their weak areas from A1.`},
    {id:'a2-2',title:'Narrative Past: Präteritum',icon:'📜',desc:'War/Hatte, modal past forms, storytelling past',
     flow:`1. Written narrative vs. spoken past tense — when Präteritum is used.\n2. Conjugation of sein in Präteritum: war, warst, war, waren, wart, waren.\n3. Conjugation of haben in Präteritum: hatte, hattest, hatte, hatten, hattet, hatten.\n4. Modal verbs in Präteritum: konnte, musste, durfte, sollte, wollte, mochte.\n5. Mixing Präteritum and Perfekt in storytelling.\n6. Hospital narratives: 'Der Patient war gestern sehr ruhig', 'Ich musste die Nachtschicht übernehmen'.`},
    {id:'a2-3',title:'Causal Clauses: Weil & Da',icon:'❓',desc:"'Because' clauses, verb-final rule",
     flow:`1. Difference between 'weil' and 'da' (both mean 'because', positional difference).\n2. Verb-final rule: subordinating conjunctions push verb to absolute end of clause.\n3. Comma placement before subordinate clauses.\n4. 'Weil' vs 'denn' — structural comparison (denn keeps V2, weil sends to end).\n5. Drills: 'Ich kann nicht kommen, weil ich krank bin'.\n6. Hospital: 'Sie müssen nüchtern bleiben, weil Sie operiert werden', 'Da er Fieber hat, bleibt er im Bett'.`},
    {id:'a2-4',title:'Conditional Clauses: Wenn & Falls',icon:'🔀',desc:"'If/when' clauses and conditionals",
     flow:`1. 'Wenn' for conditions and repeated events (if/when/whenever).\n2. 'Falls' for hypothetical or uncertain conditions (in case/if).\n3. Verb-final rule in wenn/falls clauses.\n4. Main clause inversion when the wenn-clause comes first.\n5. Drills: 'Wenn Sie Schmerzen haben, rufen Sie bitte an.' / 'Falls es schlimmer wird, kommen Sie sofort'.\n6. Hospital emergency language: conditional instructions to patients.`},
    {id:'a2-5',title:'Causal Adverbs: Deshalb & Darum',icon:'➡️',desc:"'Therefore/so' — connector adverbs with inversion",
     flow:`1. 'Deshalb', 'darum', 'deswegen' — all meaning 'therefore/that is why'.\n2. These occupy Position 1, causing inversion (verb comes before subject).\n3. Contrast with 'weil' (sends verb to end) vs 'deshalb' (keeps V2 but inverts S and V).\n4. 'Also' as a softer connector — 'so/therefore'.\n5. Sentence chains: 'Ich bin krank. Deshalb arbeite ich heute nicht'.\n6. Hospital documentation style: stating reasons for clinical decisions.`},
    {id:'a2-6',title:'Concessive Clauses: Obwohl & Trotzdem',icon:'🔄',desc:"'Although/nevertheless' — expressing contrast",
     flow:`1. 'Obwohl' (although) — subordinating conjunction, verb to end.\n2. 'Trotzdem' (nevertheless) — adverb at Position 1, triggers inversion.\n3. 'Obwohl' vs 'aber' — structural and semantic differences.\n4. Drills: 'Obwohl er Fieber hat, will er nach Hause', 'Er hat Fieber. Trotzdem will er nach Hause'.\n5. Hospital: describing patients who refuse treatment, recording non-compliance.`},
    {id:'a2-7',title:'Finality Clauses: Um...zu & Damit',icon:'🎯',desc:"'In order to' — expressing purpose",
     flow:`1. 'Um...zu + Infinitiv' — same subject in both clauses.\n2. 'Damit' + subordinate clause — different subjects in main and subordinate clause.\n3. Structural comparison with examples.\n4. Drills: 'Ich lerne Deutsch, um in Deutschland zu arbeiten', 'Ich erkläre es langsam, damit der Patient es versteht'.\n5. Hospital purpose expressions: explaining procedures, treatment goals.`},
    {id:'a2-8',title:'Indirect Speech: Dass & Ob',icon:'💬',desc:'Reported speech, dass-clauses, ob-clauses',
     flow:`1. 'Dass' (that) — reporting statements and opinions.\n2. 'Ob' (whether/if) — reporting yes/no questions in indirect speech.\n3. Verb-final rule applies to both.\n4. Verb tense in indirect speech.\n5. Drills: 'Der Arzt sagt, dass der Patient Ruhe braucht', 'Ich weiß nicht, ob er operiert wird'.\n6. Hospital: relaying doctor's instructions, documenting patient statements.`},
    {id:'a2-9',title:'Reflexive Verbs I',icon:'🔁',desc:'Accusative reflexive verbs and pronouns',
     flow:`1. Concept of reflexive verbs — subject and object are the same person.\n2. Accusative reflexive pronouns: mich, dich, sich, uns, euch, sich.\n3. Common reflexive verbs: sich waschen, sich anziehen, sich fühlen, sich setzen, sich beeilen.\n4. Position of reflexive pronoun in the sentence.\n5. Drills: 'Wie fühlen Sie sich?', 'Setzen Sie sich bitte'.\n6. Hospital: patient hygiene instructions, asking patients how they feel.`},
    {id:'a2-10',title:'Reflexive Verbs II',icon:'🔁',desc:'Dative reflexive verbs, body part expressions',
     flow:`1. Dative reflexive pronouns: mir, dir, sich, uns, euch, sich.\n2. When Dative reflexive is used — when there's another object in the sentence.\n3. Common Dative reflexive verbs: sich vorstellen, sich merken, sich wünschen.\n4. Body part structures: 'Ich wasche mir die Hände', 'Bitte putzen Sie sich die Zähne'.\n5. Hospital hygiene instructions and patient care language.`},
    {id:'a2-11',title:'Adjective Endings I',icon:'📝',desc:'Adjective endings after definite articles',
     flow:`1. Why adjectives need endings — the grammatical agreement system.\n2. Adjective endings after definite articles (der/die/das/die) — the 'weak declension'.\n3. Full tables for Nominative, Accusative, Dative across M/F/N/Plural.\n4. Drills: 'der alte Patient', 'die junge Ärztin', 'das kleine Kind'.\n5. Hospital descriptions: patient charts, diagnosis language.`},
    {id:'a2-12',title:'Adjective Endings II',icon:'📝',desc:'Adjective endings after indefinite articles',
     flow:`1. Adjective endings after indefinite articles (ein/eine/ein) — the 'mixed declension'.\n2. Where the gender signal shifts from article to adjective.\n3. Full tables for all cases across M/F/N.\n4. Drills: 'ein alter Patient', 'eine junge Ärztin', 'ein kleines Kind'.\n5. Contrast with definite article endings from the previous lesson.`},
    {id:'a2-13',title:'Adjective Endings III',icon:'📝',desc:'Strong adjective endings without articles',
     flow:`1. Adjective endings when no article is present — the 'strong declension'.\n2. The adjective itself must carry the full gender/case signal.\n3. Common contexts: after numbers, after 'viel', 'wenig', 'etwas'.\n4. Drills: 'kaltes Wasser', 'frisches Obst', 'starker Kaffee'.\n5. Hospital: 'frisches Blut', 'starke Schmerzen', 'erhöhter Blutdruck'.`},
    {id:'a2-14',title:'Comparison: Comparative',icon:'📊',desc:'Adjective comparatives, -er forms, als',
     flow:`1. Forming comparative: adjective + -er (schnell → schneller, jung → jünger).\n2. Umlaut changes: alt→älter, groß→größer, jung→jünger.\n3. Irregular comparatives: gut→besser, viel→mehr, gern→lieber.\n4. Comparison structures: 'X ist...er als Y', 'Je...desto...'.\n5. Hospital: 'Der Patient ist heute besser', 'Die neue Methode ist effektiver als die alte'.`},
    {id:'a2-15',title:'Comparison: Superlative',icon:'🏆',desc:'Superlative forms, am...sten structures',
     flow:`1. Forming superlative: am + adjective + -sten (am schnellsten, am größten).\n2. Attributive superlative: der/die/das + adjective + -st + ending.\n3. Irregular superlatives: gut→am besten, viel→am meisten, gern→am liebsten.\n4. Drills with hospital context: 'die höchste Temperatur', 'am stärksten schmerzt...'\n5. Using superlatives in patient assessment and clinical prioritization.`},
    {id:'a2-16',title:'Genitive Case',icon:'🔑',desc:'Possession, Genitive prepositions',
     flow:`1. The Genitive case for showing possession and origin.\n2. Genitive article changes: des (M/N +s/-es on noun), der (F/Pl).\n3. Genitive with names: 'Dr. Müllers Patient', 'Das Zimmer der Patientin'.\n4. Common Genitive prepositions: wegen, trotz, während, statt, aufgrund, innerhalb, außerhalb.\n5. Hospital use: 'wegen seiner Erkrankung', 'während der Operation', 'aufgrund des Befundes'.`},
    {id:'a2-17',title:'Two-Way Prepositions I',icon:'📍',desc:'In, an, auf — deep dive with Acc/Dat',
     flow:`1. Deep dive into 'in', 'an', 'auf' with full Accusative (Wohin?) vs Dative (Wo?) comparison.\n2. Special meanings: 'an' for edges/walls/days, 'auf' for flat surfaces/events, 'in' for enclosed spaces.\n3. Fixed phrases: 'im Krankenhaus', 'auf der Station', 'am Wochenende'.\n4. Contractions drill: ins/im, ans/am, aufs/auf dem.\n5. Hospital: 'Das Stethoskop hängt an der Wand', 'Legen Sie es auf den Nachttisch'.`},
    {id:'a2-18',title:'Two-Way Prepositions II',icon:'📍',desc:'Unter, über, vor, hinter, neben, zwischen',
     flow:`1. Remaining two-way prepositions: unter, über, vor, hinter, neben, zwischen.\n2. Accusative (movement) vs Dative (location) for each.\n3. Figurative meanings: 'über' (about/over), 'vor' (before/in front of/ago).\n4. Time expressions with 'vor': 'vor einer Stunde', 'vor drei Tagen'.\n5. Hospital spatial navigation: 'Das Röntgenzimmer ist neben der Aufnahme', 'Warten Sie vor dem Zimmer'.`},
    {id:'a2-19',title:'Fixed Prepositions I',icon:'🔒',desc:'Verb + preposition fixed combinations',
     flow:`1. Concept of fixed preposition combinations — preposition determined by verb, not meaning.\n2. Accusative fixed prepositions: warten auf, denken an, sich freuen auf, sich erinnern an, sich gewöhnen an.\n3. Pronominal adverbs: worauf, woran, darauf, daran.\n4. Question formation: 'Worauf warten Sie?' / 'Auf was warten Sie?'\n5. Hospital: 'Wir warten auf die Laborergebnisse', 'Ich denke an den Patienten'.`},
    {id:'a2-20',title:'Fixed Prepositions II',icon:'🔒',desc:'Adjective + preposition combinations',
     flow:`1. Adjective + preposition fixed combinations: zufrieden mit, verantwortlich für, abhängig von, interessiert an, besorgt um.\n2. Dative fixed preposition verbs: helfen bei, sprechen mit, arbeiten mit.\n3. Noun + preposition: Angst vor, Interesse an, Freude über.\n4. Drills combining pronominal adverbs with fixed prepositions.\n5. Hospital: 'Ich bin verantwortlich für den Patienten', 'Der Arzt ist zufrieden mit dem Verlauf'.`},
    {id:'a2-21',title:'Future Tense: Futur I',icon:'🔮',desc:'Werden + Infinitiv for future expressions',
     flow:`1. Futur I formation: werden (conjugated) + Infinitiv at end.\n2. Conjugation of werden: werde, wirst, wird, werden, werdet, werden.\n3. When to use Futur I vs. present tense with time marker for future.\n4. 'Werden' for predictions and assumptions: 'Er wird müde sein'.\n5. Drills: 'Ich werde morgen früh anfangen', 'Sie wird bald gesund werden'.\n6. Hospital: 'Der Arzt wird die Ergebnisse erklären', 'Die Wunde wird schnell heilen'.`},
    {id:'a2-22',title:'Konjunktiv II: Wishes & Politeness',icon:'🎭',desc:'Subjunctive II for polite requests and hypotheticals',
     flow:`1. Introduction to Konjunktiv II — usage for polite requests, unreal situations, wishes.\n2. Formation: würde + Infinitiv (the analytical form — most common).\n3. Common irregular forms: wäre, hätte, könnte, müsste, dürfte.\n4. Polite requests: 'Könnten Sie bitte...?', 'Würden Sie mir helfen?'\n5. Wishes and hypotheticals: 'Wenn ich mehr Zeit hätte...', 'Ich würde gern in München arbeiten'.\n6. Hospital: 'Könnten Sie bitte leiser sein?', 'Ich hätte gern mehr Informationen'.`},
    {id:'a2-23',title:'Professional German: The CV',icon:'📋',desc:'Lebenslauf structure, professional vocabulary',
     flow:`1. Structure of a German Lebenslauf (CV): persönliche Daten, Berufserfahrung, Ausbildung, Kenntnisse.\n2. Standard CV phrases: 'tätig als', 'zuständig für', 'Kenntnisse in'.\n3. Dates and periods: 'von... bis', 'seit', '2019–2022'.\n4. Describing qualifications: Examen, Abschluss, Zertifikat, Fortbildung.\n5. Nursing-specific CV: listing clinical placements, specializations, language certificates.\n6. German CV conventions: photo, date of birth, no gaps in timeline.`},
    {id:'a2-24',title:'Professional German: Cover Letter',icon:'📄',desc:'Anschreiben structure and professional tone',
     flow:`1. Structure of a formal Anschreiben: Betreff, Anrede, Einleitung, Hauptteil, Schluss, Grußformel.\n2. Opening phrases: 'Mit großem Interesse habe ich...', 'Hiermit bewerbe ich mich...'.\n3. Body: describing motivation, qualifications, and fit for the position.\n4. Closing: 'Über eine Einladung zum Vorstellungsgespräch freue ich mich sehr'.\n5. Formal language register throughout — no contractions, full sentences.\n6. Nursing application letter: highlighting clinical experience and language skills.`},
    {id:'a2-25',title:'Passive Voice',icon:'🔄',desc:'Passive formation and usage at A2 level',
     flow:`1. Concept: shifting focus from actor to action — when to use passive.\n2. Formation: werden (conjugated) + Partizip II at end (Vorgangspassiv).\n3. Present passive: 'Der Patient wird behandelt', 'Das Medikament wird gegeben'.\n4. Past passive (Perfekt): 'Der Patient ist behandelt worden'.\n5. Von-phrase to mention the actor: 'Der Patient wird vom Arzt untersucht'.\n6. Hospital documentation: passive voice in medical reports and instructions.`},
    {id:'a2-26',title:'Relative Clauses I',icon:'🔗',desc:'Relative clauses with Nominative and Accusative',
     flow:`1. Introduction to relative clauses — adding information about a noun.\n2. Relative pronouns in Nominative: der, die, das, die (same as definite articles).\n3. Relative pronouns in Accusative: den, die, das, die.\n4. Verb goes to the END of the relative clause.\n5. Comma before every relative clause.\n6. Drills: 'Der Arzt, der hier arbeitet...', 'Die Patientin, die ich betreue...'.\n7. Hospital: building descriptive sentences about patients, rooms, procedures.`},
    {id:'a2-27',title:'Relative Clauses II',icon:'🔗',desc:'Relative clauses with Dative and Genitive',
     flow:`1. Relative pronouns in Dative: dem, der, dem, denen.\n2. Relative pronouns in Genitive: dessen, deren, dessen, deren.\n3. Relative clauses with prepositions: 'die Station, auf der ich arbeite'.\n4. Drills: 'Der Patient, dem ich geholfen habe', 'Die Ärztin, deren Patientin ich bin'.\n5. Building professional-sounding complex sentences for hospital communication.`},
  ],
  B1:[
    {id:'b1-1',title:'B1 Welcome & Diagnostic',icon:'🎯',desc:'A2 review, B1 objectives, self-assessment',
     flow:`1. B1 course parameters, target metrics, and Goethe B1 exam structure overview.\n2. Self-assessment diagnostic: grammar, vocabulary, and speaking tasks.\n3. Comprehensive A2 grammar review: cases, conjunctions, Perfekt, passive basics.\n4. B1 learning objectives: fluent workplace communication, exam readiness.\n5. Introduction to B1 text types: reports, formal letters, complex instructions.`},
    {id:'b1-2',title:'Infinitive Constructions',icon:'∞',desc:"Infinitiv mit zu — rules, triggers, separable verbs",
     flow:`1. Defining infinitive clauses as sentence-complementing structures.\n2. 'Infinitiv mit zu': placement of 'zu' before the infinitive, or between prefix and stem for separable verbs.\n3. Triggers: after certain verbs (versuchen, empfehlen, vergessen, beginnen, hoffen), adjectives (wichtig, leicht, schwer), nouns.\n4. 'Es ist wichtig, regelmäßig die Hände zu waschen'.\n5. Separable verb: 'Es ist schwer, früh aufzustehen'.\n6. Contrast with 'um...zu' (purpose) and 'ohne...zu' (without doing).\n7. Hospital: 'Ich empfehle Ihnen, viel Wasser zu trinken', 'Vergessen Sie nicht, das Formular auszufüllen'.`},
    {id:'b1-3',title:'Advanced Cause & Contrast',icon:'⚖️',desc:'Indem, sodass, je...desto, während (contrast)',
     flow:`1. 'Indem' (by doing) — expressing means/method.\n2. 'Sodass' (so that/such that) — expressing result.\n3. 'Je...desto' (the more...the more) — proportional relationship.\n4. 'Während' as contrast (whereas) vs. 'während' as time (while).\n5. Complex drills combining multiple connector types.\n6. Hospital: 'Indem Sie regelmäßig Ihre Medikamente nehmen...', 'Je mehr er trinkt, desto besser wird er'.`},
    {id:'b1-4',title:"The Versatile Verb 'lassen'",icon:'🔓',desc:'Causative, permissive, and reflexive uses of lassen',
     flow:`1. 'Lassen' as causative: 'Ich lasse den Patienten warten' (I let/make the patient wait).\n2. 'Lassen' as permissive: 'Lassen Sie mich helfen' (Let me help).\n3. 'Sich lassen' + Infinitiv: expressing possibility passively 'Das lässt sich machen'.\n4. 'Lassen' in Perfekt: 'Ich habe ihn kommen lassen' (double infinitive in Perfekt).\n5. Hospital: 'Lassen Sie mich Ihren Blutdruck messen', 'Das lässt sich nicht vermeiden'.`},
    {id:'b1-5',title:'Consecutive & Causal Adverbs',icon:'📎',desc:'Folglich, daher, infolgedessen, weshalb',
     flow:`1. 'Folglich', 'daher', 'infolgedessen', 'somit' — consequently/therefore (formal register).\n2. 'Weshalb', 'weswegen' — interrogative connectors (why/because of which).\n3. Difference in register: daher (formal/written) vs. deshalb (spoken).\n4. Relative clause with weshalb: 'Das ist der Grund, weshalb ich hier bin'.\n5. Hospital documentation: formal causal reasoning in medical reports.`},
    {id:'b1-6',title:'The Genitiv Case (Advanced)',icon:'🔑',desc:'Genitiv in complex sentences and formal writing',
     flow:`1. Full Genitiv declension review.\n2. Genitiv in relative clauses: 'der Arzt, dessen Patient...' / 'die Ärztin, deren Patient...'\n3. Genitiv prepositions in B1 texts: anstelle, bezüglich, hinsichtlich, infolge, mithilfe.\n4. Genitiv vs. 'von + Dativ' — formal vs. colloquial usage.\n5. Hospital formal writing: 'infolge der Erkrankung', 'bezüglich des Befundes', 'mithilfe des Teams'.`},
    {id:'b1-7',title:'Genitiv Prepositions',icon:'📎',desc:'Wegen, trotz, während, statt in formal use',
     flow:`1. Deep drill on: wegen, trotz, während, statt (anstatt), aufgrund, innerhalb, außerhalb, oberhalb, unterhalb.\n2. Regional variation: wegen + Dative (colloquial) vs. Genitiv (standard).\n3. Building formal complaint and explanation sentences.\n4. Hospital: 'trotz des Fiebers', 'wegen der Erkrankung', 'während des Eingriffs', 'statt des Medikaments'.`},
    {id:'b1-8',title:'Narrative Past: Präteritum (Extended)',icon:'📜',desc:'Full Präteritum — strong verbs, patient histories',
     flow:`1. Full Präteritum paradigm for all strong (irregular) verbs: gehen→ging, kommen→kam, fahren→fuhr, schreiben→schrieb.\n2. Mixed verbs: bringen→brachte, denken→dachte, wissen→wusste.\n3. Präteritum in formal written texts and medical histories.\n4. Narrative paragraph construction using Präteritum.\n5. Hospital: writing patient histories ('Er klagte über...', 'Die Patientin kam wegen...', 'Nach der Operation verlief...').`},
    {id:'b1-9',title:'Chronological Sequencing',icon:'⏱️',desc:'Als, wenn, während, bevor, nachdem — temporal clauses',
     flow:`1. Temporal subordinate clauses: als (one-time past), wenn (repeated/present/future), während (simultaneous).\n2. 'Bevor' (before), 'nachdem' (after — with tense shift), 'seitdem' (since then).\n3. Tense sequence with 'nachdem': Plusquamperfekt in nachdem-clause if main verb is Präteritum.\n4. Building chronological patient histories.\n5. Hospital: 'Als der Patient ankam, hatte er hohes Fieber', 'Nachdem ich die Wunde versorgt hatte, rief ich den Arzt'.`},
    {id:'b1-10',title:'Konjunktiv II — Core',icon:'🌀',desc:'Hypotheticals, wishes, advice, polite requests',
     flow:`1. Full Konjunktiv II paradigm: würde + Infinitiv and direct irregular forms.\n2. Direct forms: wäre, hätte, könnte, müsste, sollte, dürfte, wollte, möchte.\n3. Konjunktiv II in conditions: 'Wenn ich Zeit hätte, würde ich mehr lernen'.\n4. Advice: 'An Ihrer Stelle würde ich...', 'Sie sollten...'.\n5. Politeness: 'Könnten Sie bitte...', 'Ich hätte gern...'.\n6. Hospital: giving recommendations, discussing treatment alternatives.`},
    {id:'b1-11',title:'Advanced Konjunktiv II',icon:'🌀',desc:'Konjunktiv II Vergangenheit — past hypotheticals',
     flow:`1. Konjunktiv II Vergangenheit: hätte/wäre + Partizip II.\n2. Expressing regret: 'Wenn ich früher gekommen wäre...'.\n3. Criticism of past actions: 'Sie hätten früher zum Arzt gehen sollen'.\n4. Mixing Konjunktiv II past and present in complex sentences.\n5. Hospital: discussing what could have been done differently, peer feedback.`},
    {id:'b1-12',title:'Intent, Goal & Purpose (Advanced)',icon:'🎯',desc:'Damit, um...zu, zwecks, formal purpose expressions',
     flow:`1. Review of 'um...zu' and 'damit' — same vs. different subject.\n2. Formal alternatives: 'zwecks + Genitiv' (for the purpose of) — written/official language.\n3. 'Zum Zweck + Genitiv': 'zum Zweck der Untersuchung'.\n4. Infinitive groups: 'ohne zu', 'anstatt zu', 'statt zu'.\n5. Hospital: formal documentation of treatment goals, referral letters.`},
    {id:'b1-13',title:'Attributive Adjectives (Advanced)',icon:'📝',desc:'Extended participial phrases before nouns',
     flow:`1. Review of all three adjective declension patterns (strong/weak/mixed).\n2. Participial adjectives: 'der behandelte Patient', 'die operierende Ärztin'.\n3. Extended attribute phrases (Partizipialattribute): 'der von Dr. Müller behandelte Patient'.\n4. Noun phrases with multiple adjectives.\n5. Hospital: clinical descriptions in written reports, discharge summaries.`},
    {id:'b1-14',title:'Expressing the Future (Advanced)',icon:'🔮',desc:'Futur I vs Futur II, assumptions, prognosis',
     flow:`1. Review of Futur I (werden + Infinitiv).\n2. Futur II: werden + Partizip II + haben/sein — completed future action.\n3. 'Er wird morgen operiert worden sein' (He will have been operated on by tomorrow).\n4. Futur I for assumptions about the present: 'Sie wird wohl schlafen'.\n5. Hospital prognosis language: 'Die Wunde wird bis Freitag verheilt sein'.`},
    {id:'b1-15',title:'Weak Masculine Nouns (N-Deklination)',icon:'📗',desc:'N-Declension nouns — der Patient and similar',
     flow:`1. Identifying N-Declension (weak masculine) nouns: end in -e or are profession/nationality words.\n2. All cases except Nominative singular get -n/-en ending.\n3. Full declension table: Patient → Patienten in all non-Nominative forms.\n4. Mixed nouns: der Name, das Herz (special cases).\n5. Hospital: 'Ich helfe dem Patienten' (not 'dem Patient'), 'der Kollegen', mastering patient terminology.`},
    {id:'b1-16',title:'Relative Clauses III',icon:'🔗',desc:"Relative clauses with prepositions, 'was' and 'wo'",
     flow:`1. Relative clauses with prepositions: 'die Station, auf der ich arbeite'.\n2. Relative pronoun 'was': after indefinites (alles, nichts, etwas, das), superlatives, and entire clauses.\n3. Relative adverbs: 'wo' (where), 'wie' (how/as), 'woher' (from where).\n4. 'Er sagt etwas, was ich nicht verstehe', 'Das ist das Beste, was wir tun können'.\n5. Hospital: complex patient descriptions, describing protocols.`},
    {id:'b1-17',title:'Relative Clauses Extended',icon:'🔗',desc:'Complex combinations, participial alternatives',
     flow:`1. Stacking relative clauses in formal text.\n2. Relative clauses modifying abstract nouns.\n3. Relative clauses in passive constructions.\n4. Participial phrase as a replacement for relative clauses.\n5. Hospital: formal case presentations, written referrals, discharge letters.`},
    {id:'b1-18',title:'The Past Perfect (Plusquamperfekt)',icon:'⏪',desc:'Hatte/war + Partizip II for prior past events',
     flow:`1. Formation: hatte/war (Präteritum) + Partizip II.\n2. When to use Plusquamperfekt: action completed BEFORE another past action.\n3. Triggered by 'nachdem', 'als', 'bevor'.\n4. Contrast: 'Als ich ankam, war er schon gegangen'.\n5. Hospital: 'Nachdem der Arzt die Diagnose gestellt hatte, bestellte er die Medikamente'.`},
    {id:'b1-19',title:'Advanced Temporal Conjunctions',icon:'⏰',desc:'Sobald, solange, bis, seit, seitdem — full system',
     flow:`1. 'Sobald' (as soon as) — verb to end, future or past.\n2. 'Solange' (as long as) — parallel duration.\n3. 'Bis' as temporal conjunction (until) — verb to end.\n4. 'Seit/seitdem' (since) — with present tense for ongoing action.\n5. Full comparison of all temporal connectors: als, wenn, während, bevor, nachdem, sobald, solange, bis, seit.\n6. Hospital: 'Sobald die Ergebnisse da sind, rufen wir Sie an', 'Bis er entlassen wird, muss er ruhen'.`},
    {id:'b1-20',title:'Correlative Connectors',icon:'🔗',desc:'Sowohl...als auch, entweder...oder, weder...noch',
     flow:`1. 'Sowohl...als auch' (both...and) — joining equal elements.\n2. 'Entweder...oder' (either...or) — presenting alternatives.\n3. 'Weder...noch' (neither...nor) — double negation.\n4. 'Nicht nur...sondern auch' (not only...but also).\n5. Drills with all four correlative pairs.\n6. Hospital: 'Sowohl der Arzt als auch die Schwester...', treatment option discussions.`},
    {id:'b1-21',title:'Alternative Modal Architecture',icon:'🎛️',desc:"Sollen in reported speech, brauchen + zu, modal particles",
     flow:`1. 'Sollen' for reported instructions: 'Der Arzt sagt, Sie sollen ruhen'.\n2. 'Lassen + Infinitiv' as modal alternative.\n3. 'Brauchen + nur/nicht + zu + Infinitiv': 'Sie brauchen nicht zu kommen' (don't need to).\n4. Modal particles: doch, mal, eben, ja — adding nuance to requests and statements.\n5. Hospital: precise instruction language, distinguishing advice from obligation.`},
    {id:'b1-22',title:'Zero-Article Declensions & Negation',icon:'🚫',desc:'Nouns without articles, kein in all cases',
     flow:`1. Nouns used without articles: professional titles ('Ich bin Krankenschwester'), materials, abstract concepts.\n2. Adjective endings without articles (strong declension review in context).\n3. 'Kein' declension in all cases: keinen, keine, keinem, keiner, keines.\n4. Double negative avoidance in German.\n5. Hospital: 'Er hat kein Fieber', 'keine Allergien bekannt', 'ohne Befund'.`},
    {id:'b1-23',title:'Passive Voice I',icon:'🔄',desc:'Vorgangspassiv — all tenses, passive with modals',
     flow:`1. Full Vorgangspassiv paradigm: all tenses.\n2. Present: 'wird behandelt'; Perfekt: 'ist behandelt worden'; Präteritum: 'wurde behandelt'.\n3. Passive with modal verbs: 'muss operiert werden', 'kann entlassen werden'.\n4. 'Von' phrase: 'wird vom Arzt untersucht'.\n5. Hospital: writing medical reports and procedural documentation in passive.`},
    {id:'b1-24',title:'Passive Voice II',icon:'🔄',desc:'Zustandspassiv, man-construction, sein + zu',
     flow:`1. Zustandspassiv (statal passive): sein + Partizip II — result/state vs. process.\n2. 'Die Tür ist geschlossen' (state) vs. 'Die Tür wird geschlossen' (process).\n3. Man-construction as active alternative: 'Man operiert ihn heute'.\n4. Sein + zu + Infinitiv (obligation passive): 'Das Formular ist auszufüllen'.\n5. Hospital: discharge reports, status descriptions, end-of-shift documentation.`},
    {id:'b1-25',title:'Nominalized Adjectives & Pronouns',icon:'📖',desc:'Substantivierte Adjektive — adjectives as nouns',
     flow:`1. Adjectives used as nouns in German (Substantivierung): capitalize, keep adjective endings.\n2. 'der Kranke' (the sick person), 'die Alte' (the old woman), 'das Wichtige' (the important thing).\n3. After 'etwas', 'nichts', 'viel', 'wenig': 'etwas Wichtiges', 'nichts Neues'.\n4. Common medical nominalized adjectives: der Verletzte, der Erkrankte, die Schwangere, der Operierte.\n5. Hospital: patient charts, case discussions using nominalized adjectives.`},
    {id:'b1-26',title:'Participial Modifiers',icon:'📝',desc:'Extended participial phrases replacing relative clauses',
     flow:`1. Present participle (Partizip I): stem + -d (arbeitend, wartend, liegend).\n2. Partizip I used as adjective before noun: 'der wartende Patient'.\n3. Extended participial phrase: 'der auf Station 3 wartende Patient' = 'der Patient, der auf Station 3 wartet'.\n4. Past participle as adjective: 'der behandelte Patient', 'die operierten Stellen'.\n5. Hospital formal texts: discharge summaries, clinical reports, referral letters.`},
    {id:'b1-27',title:'Proportional Comparison Clauses',icon:'📈',desc:'Je...desto, umso — the more...the more',
     flow:`1. 'Je + Komparativ..., desto/umso + Komparativ' — the more...the more.\n2. Word order: je-clause is a subordinate clause (verb to end), desto-clause has inversion.\n3. 'Je früher, desto besser', 'Je mehr er schläft, desto schneller erholt er sich'.\n4. 'Umso' as alternative to 'desto'.\n5. Hospital: patient prognosis, dose-response relationships, clinical observations.`},
    {id:'b1-28',title:'Synthesis & Structural Integration',icon:'🏗️',desc:'Combining B1 grammar in complex clinical texts',
     flow:`1. Building multi-clause complex sentences using all B1 connectors.\n2. Transforming simple sentences into formal written register.\n3. Active/passive alternation for stylistic variation.\n4. Modal, temporal, causal, and conditional elements combined.\n5. Hospital: writing a complete patient case summary combining all structures learned.`},
    {id:'b1-29',title:'Productive Phrasing Toolkits',icon:'🧰',desc:'Fixed hospital expressions, hedging, reporting verbs',
     flow:`1. High-frequency hospital chunks: 'Es handelt sich um...', 'Im Vordergrund steht...', 'Hinzu kommt...'.\n2. Reporting verbs: klagen über, leiden an, verneinen, bestätigen, angeben, berichten.\n3. Hedging language: 'möglicherweise', 'es ist anzunehmen', 'wahrscheinlich'.\n4. Transition phrases for formal writing: 'Darüber hinaus', 'Im Hinblick auf', 'Abschließend'.\n5. Assembling complete clinical summaries using productive chunks.`},
  ],
  B2:[
    {id:'b2-1',title:'Word Order Mastery: TeKaMoLo',icon:'📐',desc:'Temporal, Causal, Modal, Local adverb order',
     flow:`1. The TeKaMoLo rule: Time → Cause → Manner → Location in the German sentence.\n2. Why TeKaMoLo — the principle of increasing specificity.\n3. Interaction with other sentence elements: objects, pronouns, negation.\n4. 'Ich gehe jeden Tag (Te) wegen der Arbeit (Ka) zu Fuß (Mo) ins Krankenhaus (Lo)'.\n5. Common errors and correction drills.\n6. Hospital: structuring complex clinical descriptions with natural word order.`},
    {id:'b2-2',title:'Word Formation: Prefix-Based Negation',icon:'🔤',desc:'Un-, miss-, zer-, be-, er-, ver- prefixes',
     flow:`1. Negative prefixes: un- (ungesund, unmöglich), miss- (missverstehen, missachten).\n2. Separating prefixes with semantic change: los- (start action), zer- (destroy/into pieces).\n3. Productive prefix patterns: be-, er-, ver-, ent-, ge-.\n4. Compound noun formation: Krankenhaus + Arzt = Krankenhausarzt.\n5. Building B2-level vocabulary through systematic word formation.\n6. Medical terminology built from known roots.`},
    {id:'b2-3',title:'Comparative Syntax & Proportionality',icon:'📊',desc:'Advanced comparison, scale, immer + Komparativ',
     flow:`1. Review and extension of je...desto, umso.\n2. Scalar expressions: immer + Komparativ (immer besser, immer teurer).\n3. 'Genauso...wie' vs 'so...wie' vs 'ebenso...wie'.\n4. Diminishing comparison: 'nicht so...wie', 'weniger...als'.\n5. Hospital prognosis and trend language: 'Die Vitalzeichen werden immer stabiler'.`},
    {id:'b2-4',title:'Infinitive Clauses with Prepositions',icon:'∞',desc:'Ohne zu, anstatt zu, um zu — advanced use',
     flow:`1. 'Ohne + zu + Infinitiv' (without doing) — same subject as main clause.\n2. 'Anstatt/statt + zu + Infinitiv' (instead of doing).\n3. 'Um + zu + Infinitiv' for purpose — review and complex combinations.\n4. When to use 'ohne dass', 'anstatt dass', 'damit' — when subjects differ.\n5. Formal written alternatives for each construction.\n6. Hospital: procedure instructions, patient consent language.`},
    {id:'b2-5',title:'Advanced Relative Clauses',icon:'🔗',desc:'Wo-compounds, was-clauses, relative adverbs',
     flow:`1. Review of was-relative clauses after superlatives and indefinites.\n2. Wo-compounds as relative pronouns: 'womit, worüber, wobei, woran'.\n3. 'Das, worüber wir gesprochen haben...' vs 'Das, über das wir gesprochen haben'.\n4. Relative adverbs in formal texts: wo, wohin, woher, wie.\n5. Hospital: formal report writing, complex patient case descriptions.`},
    {id:'b2-6',title:'Noun-Verb Combinations (Funktionsverbgefüge)',icon:'🔧',desc:'Fixed noun-verb combinations in formal German',
     flow:`1. What are Funktionsverbgefüge: fixed noun + verb combinations replacing simple verbs.\n2. Examples: eine Entscheidung treffen (decide), in Frage stellen (question), zur Verfügung stellen (provide), in Betracht ziehen (consider).\n3. Why they appear in formal/written German — nominalization preference.\n4. Medical Funktionsverbgefüge: unter Kontrolle bringen, zum Einsatz kommen, in Behandlung nehmen.\n5. Drills: converting simple verbs to Funktionsverbgefüge and back.`},
    {id:'b2-7',title:'The Complete Passive System',icon:'🔄',desc:'All passive forms, tenses, and passive alternatives',
     flow:`1. Full passive system review: Vorgangspassiv (werden) and Zustandspassiv (sein) in ALL tenses.\n2. Passive with ALL modal verbs in all tenses.\n3. Alternatives to passive: man-construction, sein + zu + Infinitiv, lassen-construction, reflexive passive.\n4. Choosing the right passive form for medical writing.\n5. Hospital: complete passive usage in documentation, guidelines, discharge summaries.`},
    {id:'b2-8',title:'Unreal Comparisons: Konjunktiv II',icon:'🌀',desc:'Als ob, als wenn, als hätte — irrealis comparison',
     flow:`1. 'Als ob' + Konjunktiv II (as if) — verb to end.\n2. 'Als' alone with direct Konjunktiv II inversion: 'Er sieht aus, als wäre er krank'.\n3. 'Als wenn' — slightly less common, same structure.\n4. Konjunktiv II Vergangenheit in comparison clauses.\n5. Modal particles combined with als-ob for nuance and uncertainty.\n6. Hospital: describing patient presentation, uncertainty language in diagnoses.`},
    {id:'b2-9',title:'Attributive Participles (Extended Modifiers)',icon:'📝',desc:'Erweitertes Partizipialattribut — compressed noun phrases',
     flow:`1. Extended participial attributes: the German equivalent of complex relative clauses, compressed into a noun phrase.\n2. Structure: Article + [modifiers + Partizip I or II] + Noun.\n3. 'Der gestern von Dr. Müller operierte Patient' = 'der Patient, der gestern von Dr. Müller operiert wurde'.\n4. Unpacking extended attributes — both reading and writing skill.\n5. Hospital: reading and producing formal medical documents, discharge reports.`},
    {id:'b2-10',title:'Clauses of Manner & Consequence',icon:'➡️',desc:'Sodass, so...dass, indem, dadurch dass',
     flow:`1. Result clauses: 'sodass' (so that — result follows) vs 'damit' (in order that — purpose).\n2. 'So + adjective/adverb + dass': 'Er ist so krank, dass er nicht aufstehen kann'.\n3. 'Indem' (by doing): expressing means/method.\n4. 'Dadurch, dass' (through the fact that) — causal with nominalized clause.\n5. Hospital: documenting clinical chains of cause-and-effect, treatment rationale.`},
    {id:'b2-11',title:'Modal Partikeln',icon:'🗣️',desc:'Doch, mal, eben, ja, wohl, eigentlich, denn',
     flow:`1. What modal particles are: small words that add speaker attitude and nuance.\n2. 'Doch': contradiction, encouragement, softening ('Komm doch!')\n3. 'Mal': casual softener for requests ('Kommen Sie mal bitte').\n4. 'Eben/halt': resignation or obvious fact ('Das ist eben so').\n5. 'Ja': shared knowledge marker ('Das ist ja interessant').\n6. 'Wohl': probability/assumption ('Er wird wohl krank sein').\n7. 'Eigentlich': actually/in principle.\n8. 'Denn' in questions: curiosity or surprise ('Was haben Sie denn?').\n9. Hospital: sounding natural and fluent in professional German interactions.`},
  ],
}

export const NAV = [
  {id:'home',icon:'🏠',lbl:'Home'},
  {id:'curriculum',icon:'📘',lbl:'Curriculum'},
  {id:'learn',icon:'💪',lbl:'Learn Hub'},
  {id:'vocab',icon:'🔤',lbl:'Vocabulary'},
  {id:'listening',icon:'🎙️',lbl:'Listening'},
  {id:'interview',icon:'🎭',lbl:'Interview'},
  {id:'dailytest',icon:'📝',lbl:'Daily Test'},
  {id:'performance',icon:'📈',lbl:'Performance'},
  {id:'gcbuddy',icon:'🇩🇪',lbl:'GC Buddy'},
  {id:'media',icon:'🎬',lbl:'Media'},
  {id:'referral',icon:'🎁',lbl:'Refer'},
]

export const VOCAB = {
  A1:[
    {de:'Guten Morgen',en:'Good morning',hi:'सुप्रभात',ex:'Guten Morgen! Wie geht es Ihnen?'},
    {de:'die Krankenschwester',en:'nurse (female)',hi:'नर्स',ex:'Ich bin Krankenschwester.'},
    {de:'das Krankenhaus',en:'hospital',hi:'अस्पताल',ex:'Das Krankenhaus ist groß.'},
    {de:'der Arzt',en:'doctor',hi:'डॉक्टर',ex:'Der Arzt kommt gleich.'},
    {de:'der Patient',en:'patient',hi:'मरीज़',ex:'Der Patient hat Schmerzen.'},
    {de:'das Bett',en:'bed',hi:'बिस्तर',ex:'Der Patient liegt im Bett.'},
    {de:'die Schmerzen',en:'pain',hi:'दर्द',ex:'Wo haben Sie Schmerzen?'},
    {de:'das Fieber',en:'fever',hi:'बुखार',ex:'Der Patient hat Fieber.'},
    {de:'die Tablette',en:'tablet',hi:'गोली',ex:'Nehmen Sie die Tablette.'},
    {de:'Bitte / Danke',en:'please / thank you',hi:'कृपया / धन्यवाद',ex:'Danke für Ihre Hilfe.'},
    {de:'der Mund',en:'mouth',hi:'मुँह',ex:'Bitte öffnen Sie den Mund.'},
    {de:'die Hand',en:'hand',hi:'हाथ',ex:'Geben Sie mir Ihre Hand.'},
    {de:'das Herz',en:'heart',hi:'दिल',ex:'Das Herz schlägt regelmäßig.'},
    {de:'die Nase',en:'nose',hi:'नाक',ex:'Meine Nase ist verstopft.'},
    {de:'der Kopf',en:'head',hi:'सिर',ex:'Ich habe Kopfschmerzen.'},
    {de:'die Apotheke',en:'pharmacy',hi:'फार्मेसी',ex:'Die Apotheke ist um die Ecke.'},
    {de:'Ja / Nein',en:'yes / no',hi:'हाँ / नहीं',ex:'Haben Sie Schmerzen? Ja.'},
    {de:'der Arm',en:'arm',hi:'बाँह',ex:'Der Arm ist verletzt.'},
    {de:'das Bein',en:'leg',hi:'टाँग',ex:'Das Bein tut weh.'},
    {de:'gut / schlecht',en:'good / bad',hi:'अच्छा / बुरा',ex:'Wie geht es Ihnen? Gut.'},
  ],
  A2:[
    {de:'der Blutdruck',en:'blood pressure',hi:'रक्तचाप',ex:'Ich messe Ihren Blutdruck.'},
    {de:'die Allergie',en:'allergy',hi:'एलर्जी',ex:'Haben Sie eine Allergie?'},
    {de:'die Infusion',en:'IV drip',hi:'ड्रिप',ex:'Die Infusion läuft noch.'},
    {de:'der Puls',en:'pulse',hi:'नाड़ी',ex:'Der Puls ist regelmäßig.'},
    {de:'das Medikament',en:'medication',hi:'दवाई',ex:'Nehmen Sie das Medikament.'},
    {de:'die Visite',en:'ward round',hi:'विजिट',ex:'Die Visite beginnt um 8 Uhr.'},
    {de:'die Übergabe',en:'handover',hi:'हस्तांतरण',ex:'Die Übergabe um 14 Uhr.'},
    {de:'schwindelig',en:'dizzy',hi:'चक्कर',ex:'Mir ist schwindelig.'},
    {de:'die Blutgruppe',en:'blood type',hi:'रक्त समूह',ex:'Welche Blutgruppe haben Sie?'},
    {de:'das Rezept',en:'prescription',hi:'नुस्खा',ex:'Der Arzt schreibt ein Rezept.'},
    {de:'die Notaufnahme',en:'emergency dept',hi:'आपातकाल',ex:'Gehen Sie zur Notaufnahme.'},
    {de:'nüchtern',en:'fasting',hi:'उपवास',ex:'Sie müssen nüchtern bleiben.'},
    {de:'die Spritze',en:'injection',hi:'इंजेक्शन',ex:'Ich gebe Ihnen eine Spritze.'},
    {de:'die Wunde',en:'wound',hi:'घाव',ex:'Die Wunde muss verbunden werden.'},
    {de:'stationär',en:'inpatient',hi:'भर्ती',ex:'Stationär aufgenommen.'},
    {de:'die Pflege',en:'nursing care',hi:'देखभाल',ex:'Die Pflege ist wichtig.'},
    {de:'der Rollstuhl',en:'wheelchair',hi:'व्हीलचेयर',ex:'Ich brauche einen Rollstuhl.'},
    {de:'die Krankenkasse',en:'health insurance',hi:'बीमा',ex:'Welche Krankenkasse haben Sie?'},
    {de:'regelmäßig',en:'regularly',hi:'नियमित',ex:'Nehmen Sie es regelmäßig.'},
    {de:'die Übelkeit',en:'nausea',hi:'मतली',ex:'Haben Sie Übelkeit?'},
  ],
  B1:[
    {de:'die Dyspnoe',en:'breathlessness',hi:'सांस की तकलीफ',ex:'Patient klagt über Dyspnoe.'},
    {de:'der Dekubitus',en:'pressure sore',hi:'बेड सोर',ex:'Dekubitus täglich dokumentieren.'},
    {de:'die Anamnese',en:'medical history',hi:'चिकित्सा इतिहास',ex:'Anamnese vollständig erhoben.'},
    {de:'die Compliance',en:'compliance',hi:'अनुपालन',ex:'Compliance des Patienten ist gut.'},
    {de:'der Befund',en:'finding/result',hi:'निष्कर्ष',ex:'Befund ist unauffällig.'},
    {de:'die Prognose',en:'prognosis',hi:'रोगनिदान',ex:'Prognose ist günstig.'},
    {de:'postoperativ',en:'post-operative',hi:'ऑपरेशन के बाद',ex:'Postoperative Phase ist kritisch.'},
    {de:'die Nebenwirkung',en:'side effect',hi:'दुष्प्रभाव',ex:'Medikament hat Nebenwirkungen.'},
    {de:'strahlen',en:'to radiate (pain)',hi:'फैलना',ex:'Schmerz strahlt in den Arm.'},
    {de:'aufklären',en:'to inform patient',hi:'सूचित करना',ex:'Ich kläre den Patienten auf.'},
    {de:'die Rehabilitation',en:'rehabilitation',hi:'पुनर्वास',ex:'Patient braucht Rehabilitation.'},
    {de:'die Mobilisation',en:'mobilization',hi:'गतिशीलता',ex:'Mobilisation täglich steigern.'},
    {de:'die Wundversorgung',en:'wound care',hi:'घाव देखभाल',ex:'Wundversorgung täglich.'},
    {de:'die Pflegemaßnahme',en:'nursing measure',hi:'नर्सिंग उपाय',ex:'Alle Maßnahmen dokumentieren.'},
    {de:'die Schmerzskala',en:'pain scale',hi:'दर्द पैमाना',ex:'Wo auf der Schmerzskala?'},
    {de:'die Thrombose',en:'thrombosis',hi:'थ्रोम्बोसिस',ex:'Thrombose muss verhindert werden.'},
    {de:'die Lagerung',en:'positioning',hi:'स्थिति बदलना',ex:'Lagerung alle 2 Stunden.'},
    {de:'die Bewusstseinslage',en:'consciousness level',hi:'चेतना स्तर',ex:'Bewusstseinslage ist klar.'},
    {de:'die Dienstübergabe',en:'shift handover',hi:'शिफ्ट परिवर्तन',ex:'Übergabe muss vollständig sein.'},
    {de:'stabil',en:'stable',hi:'स्थिर',ex:'Vitalzeichen sind stabil.'},
  ],
  B2:[
    {de:'die Differentialdiagnose',en:'differential diagnosis',hi:'विभेदक निदान',ex:'Mehrere Erkrankungen in Betracht.'},
    {de:'interdisziplinär',en:'interdisciplinary',hi:'अंतःविषय',ex:'Interdisziplinäres Team.'},
    {de:'die Patientenautonomie',en:'patient autonomy',hi:'रोगी स्वायत्तता',ex:'Autonomie respektieren.'},
    {de:'die Schweigepflicht',en:'confidentiality',hi:'गोपनीयता',ex:'Schweigepflicht ist obligatorisch.'},
    {de:'evidenzbasiert',en:'evidence-based',hi:'साक्ष्य-आधारित',ex:'Evidenzbasierte Behandlung.'},
    {de:'indiziert',en:'indicated',hi:'संकेतित',ex:'Operation ist indiziert.'},
    {de:'kontraindiziert',en:'contraindicated',hi:'प्रतिसंकेत',ex:'Medikament ist kontraindiziert.'},
    {de:'die Ätiologie',en:'etiology',hi:'कारण',ex:'Ätiologie ist noch unklar.'},
    {de:'multidisziplinär',en:'multidisciplinary',hi:'बहु-विषयक',ex:'Multidisziplinäres Team.'},
    {de:'die Intervention',en:'intervention',hi:'हस्तक्षेप',ex:'Intervention erfolgte zeitnah.'},
    {de:'die Prävention',en:'prevention',hi:'रोकथाम',ex:'Prävention ist wichtig.'},
    {de:'die Sepsis',en:'sepsis',hi:'सेप्सिस',ex:'Sepsis sofort behandeln.'},
    {de:'die Patientenverfügung',en:'advance directive',hi:'अग्रिम निर्देश',ex:'Patientenverfügung beachten.'},
    {de:'die Qualitätssicherung',en:'quality assurance',hi:'गुणवत्ता',ex:'Qualitätssicherung ist obligatorisch.'},
    {de:'die Rekonvaleszenz',en:'convalescence',hi:'स्वास्थ्यलाभ',ex:'Rekonvaleszenz dauert lange.'},
    {de:'nosokomial',en:'hospital-acquired',hi:'अस्पताल-अर्जित',ex:'Nosokomiale Infektion vermeiden.'},
    {de:'die Compliance-Problematik',en:'compliance issues',hi:'अनुपालन समस्याएं',ex:'Compliance-Problematik besteht.'},
    {de:'resistent',en:'resistant',hi:'प्रतिरोधी',ex:'Erreger ist resistent.'},
    {de:'die Prognostik',en:'prognostics',hi:'रोगनिदान विज्ञान',ex:'Prognostik ist schwierig.'},
    {de:'infaust',en:'poor prognosis',hi:'निराशाजनक',ex:'Prognose quoad vitam infaust.'},
  ],
}

export const MEDIA = {
  A1:[
    {title:'Easy German',platform:'YouTube',type:'channel',url:'https://www.youtube.com/@EasyGerman',desc:'Real German conversations with subtitles'},
    {title:'GermanPod101 Beginner',platform:'YouTube',type:'podcast',url:'https://www.youtube.com/@germanpod101',desc:'Podcast-style A1 lessons'},
    {title:'Deutsche Welle A1',platform:'DW',type:'course',url:'https://www.dw.com/de/deutsch-lernen',desc:'Free official German A1 course'},
    {title:'Duolingo German',platform:'App',type:'app',url:'https://www.duolingo.com/course/de/en/Learn-German',desc:'Gamified daily German practice'},
  ],
  A2:[
    {title:"Nicos Weg A2",platform:'DW',type:'series',url:'https://www.dw.com/de/deutsch-lernen/nicos-weg/s-54974',desc:"DW's free video course"},
    {title:'Learn German with Anja',platform:'YouTube',type:'channel',url:'https://www.youtube.com/@LearnGermanwithAnja',desc:'Clear A2 grammar explanations'},
    {title:'Slow German Podcast',platform:'Spotify',type:'podcast',url:'https://open.spotify.com/show/1KlTm6rBSCZVMYz1GKa0tV',desc:'Short stories spoken slowly'},
    {title:'Deutsch mit Marija',platform:'YouTube',type:'channel',url:'https://www.youtube.com/@deutschmitmarija',desc:'Fun A2 grammar lessons'},
  ],
  B1:[
    {title:'DW Langsam Nachrichten',platform:'DW',type:'news',url:'https://www.dw.com/de/deutsch-lernen/nachrichten/s-8030',desc:'News spoken slowly for learners'},
    {title:'Deutsch perfekt Podcast',platform:'Spotify',type:'podcast',url:'https://open.spotify.com/show/0LF7r0OGLzGgI5CriCfpJG',desc:'Popular B1 German podcast'},
    {title:'Extra auf Deutsch',platform:'YouTube',type:'series',url:'https://www.youtube.com/results?search_query=extra+auf+deutsch',desc:'Comedy series for B1 learners'},
    {title:'Easy German B1',platform:'YouTube',type:'channel',url:'https://www.youtube.com/@EasyGerman',desc:'Street interviews with transcripts'},
  ],
  B2:[
    {title:'Tatort',platform:'ARD',type:'series',url:'https://www.ardmediathek.de/tatort',desc:'Authentic German crime drama'},
    {title:'DW In Good Shape',platform:'DW',type:'health',url:'https://www.dw.com/en/health',desc:'Health topics — perfect for nurses'},
    {title:'Der Spiegel',platform:'Web',type:'magazine',url:'https://www.spiegel.de',desc:'Authentic B2+ journalism'},
    {title:'WDR Servicezeit Gesundheit',platform:'YouTube',type:'health',url:'https://www.youtube.com/@wdr',desc:'Medical content for B2+ learners'},
  ],
}
