// 200 questions per level (10 sets × 20) — each session picks 20 randomly

export const EXERCISES = {
A1:[
{q:"'Guten Morgen' means?",opts:["Good night","Good morning","Good evening","Goodbye"],ans:1},
{q:"Article for 'Krankenhaus'?",opts:["der","die","das","den"],ans:2},
{q:"'Ich ___ Krankenschwester.'",opts:["bin","bist","ist","sind"],ans:0},
{q:"'Bitte öffnen Sie den Mund' means?",opts:["Close eyes","Open mouth","Raise arm","Breathe deeply"],ans:1},
{q:"'Wo haben Sie Schmerzen?' asks?",opts:["How bad?","Where does it hurt?","When did it start?","What type?"],ans:1},
{q:"'Das Fieber' means?",opts:["pain","cough","fever","allergy"],ans:2},
{q:"'Die Tablette' means?",opts:["bandage","syringe","tablet","glove"],ans:2},
{q:"Greeting for evening?",opts:["Guten Morgen","Guten Tag","Guten Abend","Gute Nacht"],ans:2},
{q:"'Ich brauche Hilfe' means?",opts:["I am here","I need help","I am leaving","I feel good"],ans:1},
{q:"'Das Bett' means?",opts:["chair","table","bed","door"],ans:2},
{q:"'Sie haben Fieber' means?",opts:["cough","pain","fever","allergy"],ans:2},
{q:"'Die Apotheke' means?",opts:["hospital","clinic","pharmacy","lab"],ans:2},
{q:"'Danke' means?",opts:["Please","Sorry","Hello","Thank you"],ans:3},
{q:"'Der Arzt kommt gleich' means?",opts:["Doctor left","Doctor here","Doctor coming shortly","Doctor busy"],ans:2},
{q:"'Die Hand' means?",opts:["foot","hand","head","arm"],ans:1},
{q:"'Das Herz' means?",opts:["bone","blood","heart","lung"],ans:2},
{q:"'Bitte' means?",opts:["thank you","sorry","please","goodbye"],ans:2},
{q:"'Die Nase' means?",opts:["eye","nose","ear","mouth"],ans:1},
{q:"'Ich heiße Maria' means?",opts:["I am sick","My name is Maria","I work here","I live here"],ans:1},
{q:"'Ja / Nein' means?",opts:["here/there","up/down","yes/no","left/right"],ans:2},
{q:"'Die Zunge' means?",opts:["tooth","tongue","throat","lip"],ans:1},
{q:"'Ich bin krank' means?",opts:["I am healthy","I am cold","I am sick","I am tired"],ans:2},
{q:"'Die Station' means?",opts:["pharmacy","ward","office","lab"],ans:1},
{q:"'Morgen' means?",opts:["yesterday","today","tomorrow","evening"],ans:2},
{q:"'Die Lunge' means?",opts:["heart","kidney","lung","liver"],ans:2},
{q:"'heute' means?",opts:["tomorrow","yesterday","today","soon"],ans:2},
{q:"'Ich habe Hunger' means?",opts:["I am tired","I am thirsty","I am hungry","I am cold"],ans:2},
{q:"'Das Formular' means?",opts:["medicine","form/document","room","bed"],ans:1},
{q:"'Sonntag' is?",opts:["Saturday","Sunday","Monday","Friday"],ans:1},
{q:"'Schmerzmittel' means?",opts:["sleeping pill","vitamin","painkiller","antibiotic"],ans:2},
{q:"'Die Wange' means?",opts:["chin","cheek","forehead","neck"],ans:1},
{q:"'schlafen' means?",opts:["to eat","to drink","to sleep","to walk"],ans:2},
{q:"'zwanzig' is?",opts:["12","20","22","200"],ans:1},
{q:"'Die Kurve' in hospital means?",opts:["patient chart","temperature","hallway","room"],ans:0},
{q:"'Ich komme gleich' means?",opts:["I am busy","I come later","I come right away","I cannot come"],ans:2},
{q:"'Das Pflaster' means?",opts:["bandage/plaster","tablet","syringe","glove"],ans:0},
{q:"'Bitte setzen Sie sich' means?",opts:["Stand up","Lie down","Sit down","Come in"],ans:2},
{q:"'Die Nacht' means?",opts:["day","morning","evening","night"],ans:3},
{q:"'Wie heißen Sie?' asks?",opts:["How old?","What is your name?","Where live?","How feel?"],ans:1},
{q:"'Das Blutbild' means?",opts:["blood pressure","blood type","blood count","blood test"],ans:2},
{q:"'Der Rücken' means?",opts:["chest","belly","back","shoulder"],ans:2},
{q:"'Die Schulter' means?",opts:["elbow","shoulder","wrist","knee"],ans:1},
{q:"'Der Bauch' means?",opts:["chest","stomach","back","hip"],ans:1},
{q:"'Ich bin müde' means?",opts:["I am hungry","I am cold","I am tired","I am thirsty"],ans:2},
{q:"'Bitte legen Sie sich hin' means?",opts:["Stand up","Sit down","Lie down","Come in"],ans:2},
{q:"'Das Ohr' means?",opts:["eye","nose","ear","mouth"],ans:2},
{q:"'Ich rufe den Arzt' means?",opts:["I examine you","I call the doctor","I give medicine","I check vitals"],ans:1},
{q:"'Die Temperatur messen' means?",opts:["give medicine","take temperature","check pulse","measure BP"],ans:1},
{q:"'Trinken Sie viel Wasser' means?",opts:["Eat well","Rest often","Drink lots of water","Take medicine"],ans:2},
{q:"'Der Arm' means?",opts:["leg","arm","hand","foot"],ans:1},
{q:"'Das Knie' means?",opts:["elbow","ankle","knee","hip"],ans:2},
{q:"'Montag' is?",opts:["Sunday","Monday","Tuesday","Wednesday"],ans:1},
{q:"'Die Klinik' means?",opts:["pharmacy","clinic","lab","ward"],ans:1},
{q:"'Haben Sie Schmerzen?' means?",opts:["Are you cold?","Are you hungry?","Are you in pain?","Are you tired?"],ans:2},
{q:"'Gut' means?",opts:["bad","sick","good","tired"],ans:2},
{q:"'Ich habe Durst' means?",opts:["I am hungry","I am sleepy","I am thirsty","I am cold"],ans:2},
{q:"'Der Puls' means?",opts:["blood pressure","pulse","temperature","breathing"],ans:1},
{q:"'Die Wunde' means?",opts:["bruise","wound","rash","scar"],ans:1},
{q:"'Bitte atmen Sie ein' means?",opts:["Breathe out","Hold breath","Cough","Breathe in"],ans:3},
{q:"'Die Krankenschwester' means?",opts:["doctor","nurse (female)","patient","pharmacist"],ans:1},
{q:"'Der Krankenpfleger' means?",opts:["doctor","nurse (male)","patient","technician"],ans:1},
{q:"'zehn' means?",opts:["6","8","10","12"],ans:2},
{q:"'Wie alt sind Sie?' asks?",opts:["Where are you?","How are you?","How old are you?","Who are you?"],ans:2},
{q:"'Der Rollstuhl' means?",opts:["stretcher","crutch","wheelchair","walker"],ans:2},
{q:"'Gute Nacht' is said?",opts:["morning","lunchtime","evening/night","at work"],ans:2},
{q:"'fünfzig' means?",opts:["15","25","50","500"],ans:2},
{q:"Article for 'Arzt'?",opts:["der","die","das","den"],ans:0},
{q:"Article for 'Schwester'?",opts:["der","die","das","den"],ans:1},
{q:"'Auf Wiedersehen' means?",opts:["Good morning","Good night","Goodbye","Hello"],ans:2},
{q:"'Entschuldigung' means?",opts:["Thank you","Excuse me","Please","Hello"],ans:1},
{q:"'Der Finger' means?",opts:["hand","finger","wrist","palm"],ans:1},
{q:"'Ich verstehe nicht' means?",opts:["I agree","I don't understand","I don't know","I don't want"],ans:1},
{q:"'Langsam bitte' means?",opts:["Louder please","Slowly please","Repeat please","Help please"],ans:1},
{q:"'Der Verband' means?",opts:["syringe","plaster","dressing/bandage","tablet"],ans:2},
{q:"'Das Zimmer' means?",opts:["bed","room","ward","floor"],ans:1},
{q:"'Die Toilette' means?",opts:["shower","bathroom/toilet","kitchen","office"],ans:1},
{q:"'Klingeln Sie bitte' means?",opts:["Please wait","Please call out","Please ring the bell","Please come in"],ans:2},
{q:"'Der Stuhl' means?",opts:["table","bed","chair","door"],ans:2},
{q:"'Das Fenster' means?",opts:["door","floor","window","ceiling"],ans:2},
{q:"'Hunger / Durst' means?",opts:["hot/cold","hunger/thirst","pain/itch","tired/awake"],ans:1},
{q:"'Der Fuß' means?",opts:["leg","knee","ankle","foot"],ans:3},
{q:"'links / rechts' means?",opts:["up/down","before/after","left/right","in/out"],ans:2},
{q:"'oben / unten' means?",opts:["left/right","above/below","in/out","before/after"],ans:1},
{q:"'Wann?' means?",opts:["Where?","Who?","When?","Why?"],ans:2},
{q:"'Warum?' means?",opts:["Who?","What?","When?","Why?"],ans:3},
{q:"'Das Krankenhaus ist groß' means?",opts:["Hospital near","Hospital big","Hospital clean","Hospital new"],ans:1},
{q:"'Die Krücke' means?",opts:["wheelchair","crutch","stretcher","walker"],ans:1},
{q:"'Ich bringe Ihr Essen' means?",opts:["I bring medicine","I bring your food","I check vitals","I change bandage"],ans:1},
{q:"'Können Sie mich hören?' means?",opts:["Can you see me?","Can you hear me?","Can you feel?","Understand me?"],ans:1},
{q:"'Ich bin Ihre Pflegerin' means?",opts:["I am your doctor","I am your nurse","I am your family","I am visitor"],ans:1},
{q:"'Die Spritze' means?",opts:["tablet","injection/syringe","bandage","glove"],ans:1},
{q:"'Schlaf gut' means?",opts:["Eat well","Feel better","Sleep well","Rest well"],ans:2},
{q:"'Das Licht' means?",opts:["window","light","switch","door"],ans:1},
{q:"'Der Fuß tut weh' means?",opts:["Back hurts","Head hurts","Foot hurts","Knee hurts"],ans:2},
{q:"'Guten Appetit' means?",opts:["Good night","Enjoy your meal","Good morning","Goodbye"],ans:1},
{q:"'Die Pille' means?",opts:["injection","the pill/tablet","syrup","capsule"],ans:1},
{q:"'Ich wasche meine Hände' means?",opts:["I check hands","I wash my hands","I wear gloves","I dry hands"],ans:1},
{q:"'Bitte warten Sie' means?",opts:["Please come in","Please sit down","Please wait","Please leave"],ans:2},
{q:"'Die Brille' means?",opts:["gloves","glasses","mask","hearing aid"],ans:1},
{q:"'Das Fieber ist gesunken' means?",opts:["Fever rising","Fever same","Fever has gone down","Fever critical"],ans:2},
{q:"'Wo arbeiten Sie?' means?",opts:["When do you work?","Where do you work?","Who do you work with?","Why do you work?"],ans:1},
{q:"'Ich gebe Ihnen eine Spritze' means?",opts:["I give you medicine","I give you an injection","I take your blood","I check your wound"],ans:1},
{q:"'Der Bauch tut weh' means?",opts:["Head hurts","Chest hurts","Stomach hurts","Back hurts"],ans:2},
{q:"'achtzehn' means?",opts:["8","14","16","18"],ans:3},
{q:"'Die Erkältung' means?",opts:["fever","cold/flu","headache","cough"],ans:1},
{q:"'Husten' means?",opts:["sneeze","cough","breathe","swallow"],ans:1},
{q:"'Niesen' means?",opts:["cough","sneeze","breathe","swallow"],ans:1},
{q:"'Die Erkrankung' means?",opts:["medication","illness/disease","treatment","recovery"],ans:1},
{q:"'Ich komme morgen wieder' means?",opts:["I come now","I come later","I come tomorrow","I am leaving"],ans:2},
{q:"'Wie oft?' means?",opts:["How much?","How long?","How often?","How many?"],ans:2},
{q:"'einmal täglich' means?",opts:["twice daily","once daily","three times","weekly"],ans:1},
{q:"'Die Maske' means?",opts:["gloves","apron","mask","cap"],ans:2},
{q:"'Ich nehme Ihre Temperatur' means?",opts:["I give medicine","I take your blood","I take your temperature","I check pulse"],ans:2},
{q:"'Das Blut' means?",opts:["urine","blood","saliva","sweat"],ans:1},
{q:"'Der Magen' means?",opts:["intestine","liver","stomach","kidney"],ans:2},
{q:"'Ich helfe Ihnen' means?",opts:["I examine you","I help you","I inform you","I leave you"],ans:1},
{q:"'Das Medikament wirkt' means?",opts:["Medicine expired","Medicine is ready","Medicine is working","Medicine is wrong"],ans:2},
{q:"'Bitte bleiben Sie ruhig' means?",opts:["Please sit up","Please stand up","Please stay calm","Please come in"],ans:2},
{q:"'Ich mache eine Pause' means?",opts:["I start work","I take a break","I finish work","I call the doctor"],ans:1},
{q:"'Die Allergie' means?",opts:["illness","allergy","infection","fever"],ans:1},
{q:"'kalt / warm' means?",opts:["big/small","fast/slow","cold/warm","old/new"],ans:2},
{q:"'Ich bin gleich wieder da' means?",opts:["I will be here now","I will be right back","I am leaving","I need help"],ans:1},
{q:"'Der Bauchschmerz' means?",opts:["headache","back pain","stomach ache","chest pain"],ans:2},
{q:"'Wie viele Tabletten?' asks?",opts:["When to take?","How many tablets?","Which tablets?","Why tablets?"],ans:1},
{q:"'Das Rezept' means?",opts:["bill","prescription","report","form"],ans:1},
{q:"'Er schläft' means?",opts:["He eats","He drinks","He sleeps","He walks"],ans:2},
{q:"'Die Brille' means?",opts:["hearing aid","crutch","glasses","glove"],ans:2},
{q:"Plural of 'der Arzt' is?",opts:["die Arzten","die Ärzten","die Ärzte","die Arzte"],ans:2},
{q:"'Ich wasche meine Hände' means?",opts:["I dry my hands","I wash my hands","I check my hands","I raise my hands"],ans:1},
{q:"'Das Blut' means?",opts:["urine","saliva","sweat","blood"],ans:3},
{q:"'Bitte husten Sie' means?",opts:["Please sneeze","Please breathe","Please cough","Please swallow"],ans:2},
{q:"'Die Erkältung' means?",opts:["allergy","cold/flu","fever","infection"],ans:1},
],
A2:[
{q:"'Blutdruck ist erhöht' means?",opts:["BP low","BP normal","BP elevated","BP dangerous"],ans:2},
{q:"'Wann haben Sie zuletzt gegessen?' means?",opts:["What did you eat?","When did you last eat?","Do you eat well?","How much?"],ans:1},
{q:"Dative: 'Ich gebe ___ Patienten Tabletten'",opts:["der","die","dem","den"],ans:2},
{q:"'Nüchtern bleiben' means?",opts:["stay in bed","stay fasting","stay calm","stay quiet"],ans:1},
{q:"'Die Visite beginnt um 8 Uhr'",opts:["7:00","8:00","9:00","10:00"],ans:1},
{q:"'Können Sie tief einatmen?' means?",opts:["Breathe out deeply","Hold breath","Breathe in deeply","Cough"],ans:2},
{q:"'Patient ist bettlägerig' means?",opts:["Can walk","Is bedridden","Is discharged","Is restless"],ans:1},
{q:"'Die Wunde blutet' means?",opts:["Wound healing","Wound infected","Wound bleeding","Wound painful"],ans:2},
{q:"'schwindelig' means?",opts:["painful","tired","dizzy","nauseous"],ans:2},
{q:"'Das Rezept' means?",opts:["appointment","prescription","report","result"],ans:1},
{q:"Accusative: 'Bitte nehmen Sie ___ Tablette'",opts:["die","der","dem","das"],ans:0},
{q:"'Stationär aufgenommen' means?",opts:["Outpatient visit","Admitted inpatient","Discharged","Emergency"],ans:1},
{q:"'Übelkeit' means?",opts:["headache","nausea","fever","dizziness"],ans:1},
{q:"'Die Notaufnahme' means?",opts:["ward","clinic","emergency dept","pharmacy"],ans:2},
{q:"'Regelmäßig einnehmen' means?",opts:["Take as needed","Take once","Take regularly","Take with food"],ans:2},
{q:"'Kann ich Ihnen helfen?' means?",opts:["Can I help you?","Can you help me?","Do I need help?","Who needs help?"],ans:0},
{q:"'Die Blutgruppe' means?",opts:["blood pressure","blood type","blood test","blood count"],ans:1},
{q:"'Fieber ist gesunken' means?",opts:["Fever risen","Fever same","Fever gone down","Fever critical"],ans:2},
{q:"'Bitte unterschreiben Sie hier' means?",opts:["Wait here","Sign here","Sit here","Read this"],ans:1},
{q:"'Die Entlassung' means?",opts:["admission","operation","discharge","transfer"],ans:2},
{q:"'Wann wurden Sie geboren?' asks?",opts:["Where born?","When born?","Who parents?","What is job?"],ans:1},
{q:"'Das Zimmer ist belegt' means?",opts:["Room clean","Room available","Room occupied","Room empty"],ans:2},
{q:"'Bitte atmen Sie aus' means?",opts:["Breathe in","Hold breath","Breathe out","Cough"],ans:2},
{q:"'Die Krankheit dauert schon lange' means?",opts:["Illness just started","Illness serious","Illness lasting long","Illness contagious"],ans:2},
{q:"'Haben Sie Vorerkrankungen?' means?",opts:["Allergies?","Pre-existing conditions?","Family?","Insurance?"],ans:1},
{q:"'Erhöhte Temperatur' means?",opts:["Low temp","Normal temp","Elevated temp","No temp"],ans:2},
{q:"'Die Krankenhausaufnahme' means?",opts:["discharge","transfer","admission","bill"],ans:2},
{q:"'Der Sauerstoff' means?",opts:["nitrogen","oxygen","carbon dioxide","air"],ans:1},
{q:"'Die Übergabe' means?",opts:["admission","surgery","handover","discharge"],ans:2},
{q:"'Zustand stabil' means?",opts:["condition critical","condition worsening","condition stable","condition unknown"],ans:2},
{q:"'ambulant' means?",opts:["inpatient","emergency","outpatient","intensive care"],ans:2},
{q:"'Ich trage Handschuhe' means?",opts:["I wash hands","I wear gloves","I wear mask","I use sanitizer"],ans:1},
{q:"'Die Körperpflege' means?",opts:["body temperature","personal hygiene","body weight","body scan"],ans:1},
{q:"'Sturzgefährdet' means?",opts:["infection risk","fall risk","bleeding risk","confusion risk"],ans:1},
{q:"'Die Atmung ist flach' means?",opts:["breathing normal","breathing fast","breathing shallow","breathing slow"],ans:2},
{q:"'Aufrecht sitzen' means?",opts:["lie flat","sit upright","lie on side","stand up"],ans:1},
{q:"'Der Patient ist orientiert' means?",opts:["confused","sleeping","alert and oriented","agitated"],ans:2},
{q:"'Hygienevorschriften einhalten' means?",opts:["Ignore hygiene","Follow hygiene rules","Create rules","Report issues"],ans:1},
{q:"'Die Konsultation' means?",opts:["medication","examination","consultation","documentation"],ans:2},
{q:"'Trinkmenge dokumentieren' means?",opts:["Document food","Document fluid intake","Document meds","Document sleep"],ans:1},
{q:"'Bitte erscheinen Sie nüchtern' means?",opts:["Come early","Come fasting","Come with family","Come rested"],ans:1},
{q:"'Der Patient ist inkontinent' means?",opts:["confused","aggressive","incontinent","bedridden"],ans:2},
{q:"'Bitte husten Sie in die Ellenbeuge' means?",opts:["Cough into mask","Cough into elbow","Cough into hand","Cough freely"],ans:1},
{q:"'Die Pflegekraft' means?",opts:["patient","doctor","nursing staff","pharmacist"],ans:2},
{q:"'Ein- und Ausfuhr kontrollieren' means?",opts:["Monitor BP","Monitor intake/output","Monitor temp","Monitor pain"],ans:1},
{q:"'Zweimal täglich' means?",opts:["once daily","twice daily","three times","weekly"],ans:1},
{q:"'Die Wundauflage wechseln' means?",opts:["Remove wound","Change wound dressing","Clean wound","Stitch wound"],ans:1},
{q:"'Ich bereite die Infusion vor' means?",opts:["I give infusion","I stop infusion","I prepare infusion","I check infusion"],ans:2},
{q:"'Enterale Ernährung' means?",opts:["oral nutrition","IV nutrition","tube feeding","parenteral nutrition"],ans:2},
{q:"'Die Lagerung' in nursing means?",opts:["medicine storage","patient positioning","discharge planning","admission"],ans:1},
{q:"'Die Blutentnahme' means?",opts:["blood pressure check","blood transfusion","blood draw","blood type test"],ans:2},
{q:"'Haben Sie Schwindel?' means?",opts:["Have you pain?","Do you have dizziness?","Are you tired?","Have you fever?"],ans:1},
{q:"'Die Krankenkasse' means?",opts:["hospital bill","health insurance","pharmacy","doctor's office"],ans:1},
{q:"'Der Befund zeigt...' means?",opts:["The treatment shows...","The finding/result shows...","The patient shows...","The nurse shows..."],ans:1},
{q:"'Schmerzen auf Skala 1-10' means?",opts:["measure BP 1-10","pain scale 1-10","heart rate 1-10","temperature 1-10"],ans:1},
{q:"'Bitte drehen Sie sich auf die Seite' means?",opts:["Stand up","Sit upright","Turn onto your side","Lie flat"],ans:2},
{q:"'Ihr Sauerstoffwert ist gut' means?",opts:["BP is good","Pulse is good","Oxygen level is good","Temperature is good"],ans:2},
{q:"'Die Physiotherapie' means?",opts:["occupational therapy","physiotherapy","speech therapy","diet therapy"],ans:1},
{q:"'Wir entlassen Sie morgen' means?",opts:["We admit you tomorrow","We operate tomorrow","We discharge you tomorrow","We transfer you tomorrow"],ans:2},
{q:"'Die Untersuchung' means?",opts:["treatment","examination","medication","surgery"],ans:1},
{q:"'Messen Sie den Puls' means?",opts:["Take blood pressure","Measure the pulse","Take temperature","Measure oxygen"],ans:1},
{q:"'Der Katheter' means?",opts:["IV drip","catheter","oxygen tube","feeding tube"],ans:1},
{q:"'Bitte nüchtern ab Mitternacht' means?",opts:["Fast after midnight","Drink after midnight","Eat after midnight","Sleep after midnight"],ans:0},
{q:"'Ich dokumentiere die Vitaldaten' means?",opts:["I measure vitals","I document vital data","I report vitals","I discuss vitals"],ans:1},
{q:"'Die Antibiotika' means?",opts:["painkillers","antibiotics","vitamins","blood thinners"],ans:1},
{q:"Correct dative: 'Ich helfe ___ Patientin'",opts:["die","der","dem","das"],ans:1},
{q:"'Wundversorgung' means?",opts:["wound surgery","wound care","wound infection","wound scar"],ans:1},
{q:"'Die Stationsärztin' means?",opts:["ward nurse","ward doctor (female)","ward pharmacist","ward manager"],ans:1},
{q:"'Bitte halten Sie durch' means?",opts:["Please hold still","Please hang in there","Please breathe","Please open mouth"],ans:1},
{q:"'Die Diagnose lautet...' means?",opts:["The treatment is...","The diagnosis is...","The medication is...","The test is..."],ans:1},
{q:"'Ich nehme Blut ab' means?",opts:["I give blood","I take blood sample","I test blood","I transfuse blood"],ans:1},
{q:"'Sie dürfen aufstehen' means?",opts:["You must lie down","You may stand up","You cannot move","You need help"],ans:1},
{q:"'Die Physiotherapeutin kommt heute' means?",opts:["Doctor comes today","Physiotherapist comes today","Pharmacist comes today","Family comes today"],ans:1},
{q:"'Ich erkläre Ihnen die Medikamente' means?",opts:["I give you meds","I explain your meds","I prepare meds","I check meds"],ans:1},
{q:"'Bitte zeigen Sie Ihre Versicherungskarte' means?",opts:["Show your ID","Show your insurance card","Show your prescription","Show your results"],ans:1},
{q:"'Das Labor hat Ihren Befund geschickt' means?",opts:["Lab sent appointment","Lab sent your result","Lab sent medicine","Lab sent bill"],ans:1},
{q:"'Der Blutdruck ist heute normal' means?",opts:["BP high today","BP normal today","BP low today","BP not measured"],ans:1},
{q:"'Die Infusion läuft noch' means?",opts:["Infusion finished","Infusion is still running","Infusion not started","Infusion removed"],ans:1},
{q:"'Bitte trinken Sie viel' means?",opts:["Please eat much","Please drink a lot","Please sleep well","Please rest"],ans:1},
{q:"'Ich gebe Ihnen Schmerzmittel' means?",opts:["I give you vitamins","I give you painkillers","I give you antibiotics","I give you sleeping pills"],ans:1},
{q:"'Haben Sie heute Stuhlgang gehabt?' means?",opts:["Did you eat today?","Did you drink today?","Did you have a bowel movement?","Did you sleep?"],ans:2},
{q:"'Die Naht' means?",opts:["wound","scar","suture/stitch","bandage"],ans:2},
{q:"'Ich wasche die Wunde' means?",opts:["I examine wound","I wash the wound","I close wound","I bandage wound"],ans:1},
{q:"'Das Thermometer zeigt 38,5°C' — what is this?",opts:["Normal temp","Low fever","Normal fever","High fever"],ans:1},
{q:"'Die Nebenwirkungen' means?",opts:["main effects","side effects","allergic reactions","overdose effects"],ans:1},
{q:"'Bitte sagen Sie mir, wenn es weh tut' means?",opts:["Tell me if you're tired","Tell me if it hurts","Tell me if you're cold","Tell me if you're hungry"],ans:1},
{q:"'Die Visite' means?",opts:["visit from family","ward round","night shift","morning meeting"],ans:1},
{q:"'Ich stelle den Rollstuhl bereit' means?",opts:["I move the bed","I prepare the wheelchair","I call doctor","I prepare medicine"],ans:1},
{q:"'Sie müssen im Bett bleiben' means?",opts:["You may get up","You must stay in bed","You should eat","You can go home"],ans:1},
{q:"'Die Krankheit heilt gut' means?",opts:["Illness is serious","Illness is healing well","Illness is worsening","Illness is chronic"],ans:1},
{q:"Correct: 'Morgen ___ die Operation.'",opts:["ist","wird","hat","war"],ans:1},
{q:"'Die Einweisung' means?",opts:["prescription","hospital referral/admission","appointment","transfer form"],ans:1},
{q:"'Nüchtern bleiben' means?",opts:["Stay awake","Stay fasting","Stay calm","Stay in bed"],ans:1},
{q:"'Die Sauerstoffsättigung' means?",opts:["blood sugar","oxygen saturation","blood pressure","heart rate"],ans:1},
{q:"'Ich lege Ihnen eine Infusion' means?",opts:["I give you a tablet","I put in an IV drip","I change your bandage","I check your pulse"],ans:1},
{q:"'Der Befund ist unauffällig' means?",opts:["Result is abnormal","Result is normal/unremarkable","Result is missing","Result is urgent"],ans:1},
{q:"'Die Physiotherapie' means?",opts:["occupational therapy","speech therapy","physiotherapy","psychology"],ans:2},
{q:"'stationär aufgenommen' means?",opts:["discharged","transferred","admitted as inpatient","referred"],ans:2},
{q:"'Der Zustand ist stabil' means?",opts:["Condition is worsening","Condition is stable","Condition is critical","Condition improved"],ans:1},
{q:"'Ich dokumentiere die Pflegemaßnahmen' means?",opts:["I cancel care","I document care measures","I plan care","I review care"],ans:1},
{q:"'Die Einwilligung' means?",opts:["rejection","complaint","consent","referral"],ans:2},
{q:"'Wie lange dauert das?' asks?",opts:["How much does it cost?","How long does it take?","How often?","How painful?"],ans:1},
],
B1:[
{q:"'Klagt über Dyspnoe' means?",opts:["Good breathing","Breathlessness complaints","No problems","Recovered"],ans:1},
{q:"'obwohl' means?",opts:["because","if","although","so that"],ans:2},
{q:"'sobald' means?",opts:["although","as soon as","before","after"],ans:1},
{q:"'Der Befund ist unauffällig' means?",opts:["Results critical","Results normal/unremarkable","Results missing","Results wrong"],ans:1},
{q:"'Ich passe die Dosis an' means?",opts:["I prescribe","I adjust the dose","I stop medicine","I double dose"],ans:1},
{q:"'Schmerzen strahlen in linken Arm' means?",opts:["Right arm pain","Pain radiates to left arm","Chest pain","Leg pain"],ans:1},
{q:"Perfekt of 'nehmen'?",opts:["hat genommen","hat genehmt","ist genommen","hat nehmen"],ans:0},
{q:"'Trotz Therapie' means?",opts:["because of therapy","before therapy","despite therapy","after therapy"],ans:2},
{q:"'Die Prognose ist gut' means?",opts:["Diagnosis clear","Treatment ready","Outlook/prognosis good","Condition serious"],ans:2},
{q:"'Patient lehnt Behandlung ab' means?",opts:["Accepts treatment","Requests treatment","Refuses treatment","Needs treatment"],ans:2},
{q:"'Mobilisation schrittweise steigern' means?",opts:["Stop mobilization","Gradually increase","Already happened","Not needed"],ans:1},
{q:"'falls' means?",opts:["because","although","if","when"],ans:2},
{q:"'weil' introduces?",opts:["condition","reason","contrast","result"],ans:1},
{q:"'Rücksprache mit dem Arzt' means?",opts:["Argue with doctor","Consult doctor","Ignore doctor","Replace doctor"],ans:1},
{q:"'Laborergebnisse ausstehend' means?",opts:["Results ready","Results pending","Results normal","Results negative"],ans:1},
{q:"'Die Wunde granuliert' means?",opts:["Wound infected","Wound healing (granulating)","Wound hurting","Wound bleeding"],ans:1},
{q:"'damit' introduces?",opts:["concessive","purpose","causal","conditional"],ans:1},
{q:"Passive: 'Tablette wird eingenommen' means?",opts:["Nurse gives it","Patient takes it","Tablet is being taken","Doctor prescribes"],ans:2},
{q:"'bevor' means?",opts:["after","while","before","because"],ans:2},
{q:"'Übergabe erfolgt strukturiert' means?",opts:["Handover skipped","Structured handover done","Brief handover","No handover"],ans:1},
{q:"'Der Patient ist ansprechbar' means?",opts:["unconscious","responsive","sleeping","confused"],ans:1},
{q:"'Thromboseprophylaxe' means?",opts:["wound care","clot treatment","thrombosis prevention","blood thinning"],ans:2},
{q:"'Anhand der Laborwerte' means?",opts:["despite lab values","based on lab values","before lab values","after lab values"],ans:1},
{q:"'Weder...noch' means?",opts:["either...or","both...and","neither...nor","not only...but also"],ans:2},
{q:"'Bedarfsmedikation' means?",opts:["regular meds","PRN / as needed meds","morning meds","IV meds"],ans:1},
{q:"'Symptome haben sich aggraviert' means?",opts:["Symptoms improved","Symptoms stable","Symptoms worsened","Symptoms gone"],ans:2},
{q:"'Pflegediagnose' means?",opts:["medical diagnosis","nursing diagnosis","discharge diagnosis","final diagnosis"],ans:1},
{q:"'Nach Rücksprache' means?",opts:["without consulting","before consulting","after consulting","instead of consulting"],ans:2},
{q:"'Stabil aber kritisch' means?",opts:["Improving rapidly","Stable but critical","Recovering well","Unstable improving"],ans:1},
{q:"'Die Entlassungsplanung' means?",opts:["admission planning","discharge planning","treatment planning","surgery planning"],ans:1},
{q:"'Wundversorgung täglich' means?",opts:["Wound surgery daily","Daily wound care","Weekly wound check","Wound needs surgery"],ans:1},
{q:"'Patient verweigert Nahrungsaufnahme' means?",opts:["Eating well","Needs feeding","Refuses to eat","Is fasting voluntarily"],ans:2},
{q:"'Vitalzeichenkontrolle' means?",opts:["medication check","vital signs monitoring","wound check","blood sugar check"],ans:1},
{q:"'Ich leite sofortige Maßnahmen ein' means?",opts:["I delay measures","I plan future","I initiate immediate measures","I cancel measures"],ans:2},
{q:"'Der Patient wurde umgelagert' — passive means?",opts:["Repositioned himself","Was repositioned","Needs repositioning","Refused"],ans:1},
{q:"'Komplikationsarm' means?",opts:["many complications","severe complications","few complications","no complications"],ans:2},
{q:"'Ich sichere Patienten gegen Sturz' means?",opts:["Help patient walk","Secure against falls","Lift patient","Transfer patient"],ans:1},
{q:"'Unter maximaler konservativer Therapie'",opts:["no treatment","minimal treatment","maximum conservative treatment","surgery"],ans:2},
{q:"'Ich kläre präoperativ auf' means?",opts:["Inform post-op","Inform pre-op","Examine patient","Treat patient"],ans:1},
{q:"'Blutwerte im Normbereich' means?",opts:["abnormal values","critical values","within normal range","improving values"],ans:2},
{q:"'Die Dekubitusprophylaxe' means?",opts:["wound treatment","pressure sore prevention","scar reduction","infection control"],ans:1},
{q:"'Postoperativ engmaschig überwachen' means?",opts:["Monitor pre-op loosely","Monitor post-op closely","Stop monitoring","Monitor weekly"],ans:1},
{q:"'Ich führe die Pflege durch' means?",opts:["I plan care","I carry out care","I document care","I hand over care"],ans:1},
{q:"'Die Bewusstseinslage' means?",opts:["vital signs","consciousness level","pain level","temperature"],ans:1},
{q:"'Aspirationsgefahr beachten' means?",opts:["Note fall risk","Note aspiration risk","Note infection risk","Note allergy risk"],ans:1},
{q:"'Konjunktiv II' of 'können' is?",opts:["kann","konnte","könnte","gekonnt"],ans:2},
{q:"'Obwohl er Fieber hat, ist er ruhig' — 'obwohl' starts a?",opts:["causal clause","purpose clause","concessive clause","temporal clause"],ans:2},
{q:"'Ich weise den Patienten auf Risiken hin' means?",opts:["I ignore risks","I point out risks to patient","I treat the risks","I document risks"],ans:1},
{q:"'Die Fachpflege' means?",opts:["basic care","specialized nursing care","emergency care","family care"],ans:1},
{q:"'Schmerzscore dokumentieren' means?",opts:["Give pain meds","Document pain score","Treat pain","Assess pain verbally"],ans:1},
{q:"'Der Arzt hat die Diagnose mitgeteilt' means?",opts:["Doctor asked diagnosis","Doctor communicated diagnosis","Doctor made diagnosis","Doctor changed diagnosis"],ans:1},
{q:"'Kontinuierliche Überwachung' means?",opts:["Hourly monitoring","Daily monitoring","Continuous monitoring","Weekly monitoring"],ans:2},
{q:"'Die Schmerzmedikation anpassen' means?",opts:["Stop pain meds","Adjust pain medication","Start pain meds","Document pain meds"],ans:1},
{q:"'Ich leite die Grundpflege ein' means?",opts:["I finish basic care","I initiate basic care","I document basic care","I skip basic care"],ans:1},
{q:"'Wundkontrolle täglich' means?",opts:["Wound surgery daily","Daily wound check","Weekly wound care","Wound monitoring monthly"],ans:1},
{q:"'Der Patient ist desorientiertd' means?",opts:["Patient is oriented","Patient is disoriented","Patient is calm","Patient is cooperative"],ans:1},
{q:"'Ich informiere die Stationsärztin' means?",opts:["I ignore the ward doctor","I inform the ward doctor","I replace the ward doctor","I argue with ward doctor"],ans:1},
{q:"'Dabei ist zu beachten, dass...' means?",opts:["It should be ignored that...","It should be noted that...","It was decided that...","It was forgotten that..."],ans:1},
{q:"'Die Pflegeplanung' means?",opts:["care documentation","nursing care plan","care evaluation","care handover"],ans:1},
{q:"'Unter Beobachtung stellen' means?",opts:["Remove from observation","Place under observation","End observation","Start treatment"],ans:1},
{q:"'Ich erkläre dem Patienten den Ablauf' means?",opts:["I ask patient about procedure","I explain procedure to patient","I skip explanation","I document procedure"],ans:1},
{q:"'Die Übergabe ist vollständig' means?",opts:["Handover is skipped","Handover is complete","Handover is brief","Handover is delayed"],ans:1},
{q:"'Kooperation des Patienten' means?",opts:["Patient's cooperation","Patient's medication","Patient's diagnosis","Patient's condition"],ans:0},
{q:"'seitdem' means?",opts:["since then / ever since","before that","after that","until that"],ans:0},
{q:"'Ich halte die Hygiene ein' means?",opts:["I ignore hygiene","I document hygiene","I maintain hygiene","I teach hygiene"],ans:2},
{q:"'Die Maßnahmen sind indiziert' means?",opts:["Measures not needed","Measures are indicated","Measures are risky","Measures are finished"],ans:1},
{q:"'Ich führe ein Aufnahmegespräch durch' means?",opts:["I conduct discharge talk","I conduct admission interview","I skip interview","I write care plan"],ans:1},
{q:"'Der Verlauf ist positiv' means?",opts:["Progress is negative","Progress is uncertain","Progress is positive","Progress is stable"],ans:2},
{q:"'Sturzprotokoll ausfüllen' means?",opts:["Fill in drug chart","Fill in fall protocol","Fill in discharge form","Fill in care plan"],ans:1},
{q:"'Die Rehabilitation beginnt frühzeitig' means?",opts:["Rehab starts late","Rehab starts early","Rehab is cancelled","Rehab is planned"],ans:1},
{q:"Correct Passiv: 'Der Verband ___ täglich gewechselt.'",opts:["hat","ist","wird","war"],ans:2},
{q:"'Ich führe die Vitalwerte auf' means?",opts:["I take vitals","I record vitals","I explain vitals","I improve vitals"],ans:1},
{q:"'notwenig' means?",opts:["optional","important","necessary","urgent"],ans:2},
{q:"'Die Lagerungsmaßnahmen' means?",opts:["transport measures","positioning measures","medication measures","discharge measures"],ans:1},
{q:"'Ich spreche mit der Familie' means?",opts:["I ignore the family","I speak with the family","I call the family","I inform family by letter"],ans:1},
{q:"'Kontraindikation besteht' means?",opts:["Indication exists","Contraindication exists","Treatment is starting","No contraindication"],ans:1},
{q:"'Ich überwache die Infusion' means?",opts:["I stop infusion","I start infusion","I monitor infusion","I document infusion"],ans:2},
{q:"'Die Pflegedokumentation ist vollständig' means?",opts:["Documentation is missing","Documentation is complete","Documentation is late","Documentation is incorrect"],ans:1},
{q:"'Wir passen den Plan an' means?",opts:["We cancel the plan","We follow the plan","We adjust the plan","We start the plan"],ans:2},
{q:"'Die Anamnese erheben' means?",opts:["Give diagnosis","Take medical history","Write report","Plan treatment"],ans:1},
{q:"'Wundversorgung täglich durchführen' means?",opts:["Check wound weekly","Perform daily wound care","Document wound","Dress wound once"],ans:1},
{q:"'Der Patient klagt über Schwindel' means?",opts:["Patient complains of nausea","Patient complains of dizziness","Patient complains of pain","Patient complains of fatigue"],ans:1},
{q:"'Thromboseprophylaxe' means?",opts:["Infection prevention","Thrombosis prevention","Pain prevention","Fall prevention"],ans:1},
{q:"'nachdem' triggers which tense in its clause?",opts:["Präsens","Futur","Plusquamperfekt","Konjunktiv"],ans:2},
{q:"'indem' means?",opts:["although","because","by doing / by means of","so that"],ans:2},
{q:"'Die Mobilisation steigern' means?",opts:["Reduce mobility","Increase mobilization","Stop mobilization","Document mobility"],ans:1},
{q:"'Ich halte Rücksprache mit dem Arzt' means?",opts:["I inform the patient","I consult with the doctor","I write the report","I call the family"],ans:1},
{q:"'sobald' means?",opts:["as long as","until","as soon as","since"],ans:2},
{q:"'Die Vitalzeichen engmaschig überwachen' means?",opts:["Check vitals once","Monitor vitals closely","Record vitals weekly","Ignore vitals"],ans:1},
],
B2:[
{q:"'Symptomatik unspezifisch' means?",opts:["Clear symptoms","Non-specific symptoms","Severe symptoms","Improving symptoms"],ans:1},
{q:"'Entscheidung obliegt dem Arzt' means?",opts:["Patient decides","Nurse decides","Doctor decides","Family decides"],ans:2},
{q:"'Compliance eingeschränkt' means?",opts:["Fully compliant","Limited compliance","Very cooperative","Excellent compliance"],ans:1},
{q:"'indiziert' means?",opts:["contraindicated","indicated/appropriate","optional","dangerous"],ans:1},
{q:"'kontraindiziert' means?",opts:["indicated","recommended","contraindicated","optional"],ans:2},
{q:"'Ätiologie unklar' means?",opts:["Cause clear","Cause unknown","Treatment known","Prognosis good"],ans:1},
{q:"'evidenzbasiert' means?",opts:["traditional","evidence-based","experimental","optional"],ans:1},
{q:"'Aufklärung obligatorisch' means?",opts:["Education optional","Patient education mandatory","Doctor decides","Family decides"],ans:1},
{q:"Konjunktiv II: 'früher behandelt worden ___'?",opts:["wurde","worden wäre","war","würde"],ans:1},
{q:"'Restitutio ad integrum unwahrscheinlich' means?",opts:["Recovery very likely","Recovery certain","Full recovery unlikely","Recovery happening"],ans:2},
{q:"'Differentialdiagnose' means?",opts:["one clear diagnosis","differential diagnosis","final diagnosis","no diagnosis"],ans:1},
{q:"'Unter Berücksichtigung aller Befunde' means?",opts:["Ignoring all findings","Considering all findings","Despite findings","Before findings"],ans:1},
{q:"'wenngleich' is similar to?",opts:["weil","wenn","obwohl","damit"],ans:2},
{q:"'Ich würde empfehlen' expresses?",opts:["direct order","polite recommendation","question","diagnosis"],ans:1},
{q:"'Laborwerte deuten auf Anämie' means?",opts:["Exclude anemia","Confirm anemia","Suggest anemia","Normal values"],ans:2},
{q:"'interdisziplinär' means?",opts:["single-discipline","interdisciplinary","multicultural","international"],ans:1},
{q:"'Es steht außer Frage' means?",opts:["Questionable","Without doubt","Hypothetical","Conditional"],ans:1},
{q:"'Zeitkritisch' means?",opts:["not urgent","time-sensitive","time-consuming","time-limited"],ans:1},
{q:"'Therapie wird eskaliert' means?",opts:["Therapy stopped","Therapy reduced","Therapy intensified","Therapy documented"],ans:2},
{q:"'Patientenverfügung' means?",opts:["patient bill","patient file","advance directive","patient transfer"],ans:2},
{q:"'Indikation ist gegeben' means?",opts:["Indication absent","Indication present","Indication uncertain","Indication removed"],ans:1},
{q:"'Heilungsverlauf ist protrahiert' means?",opts:["Healing rapid","Healing complete","Healing prolonged","Healing stopped"],ans:2},
{q:"'Symptome sind rückläufig' means?",opts:["Symptoms worsening","Symptoms stable","Symptoms subsiding","Symptoms new"],ans:2},
{q:"'Es besteht Handlungsbedarf' means?",opts:["No action needed","Action taken","Action required","Action optional"],ans:2},
{q:"'Therapieadhärenz unzureichend' means?",opts:["Good adherence","Excellent adherence","Insufficient adherence","Improving adherence"],ans:2},
{q:"'Multimorbidität' means?",opts:["one disease","multiple medications","multiple simultaneous diseases","multiple allergies"],ans:2},
{q:"'Unter palliativer Intention' means?",opts:["curative intent","diagnostic intent","palliative intent","preventive intent"],ans:2},
{q:"'Aufklärung wurde durchgeführt' is?",opts:["active present","passive present","active past","passive past (Perfekt)"],ans:3},
{q:"'Therapie wird deeskaliert' means?",opts:["Therapy intensified","Therapy started","Therapy stepped down","Therapy documented"],ans:2},
{q:"'Nosokomial' means?",opts:["community-acquired","hospital-acquired","hereditary","occupational"],ans:1},
{q:"'Komorbiditäten berücksichtigen' means?",opts:["Ignore comorbidities","Treat comorbidities first","Take comorbidities into account","Document comorbidities only"],ans:2},
{q:"'Gesamtprognose verhalten optimistisch' means?",opts:["Very good prognosis","Poor prognosis","Cautiously optimistic prognosis","Uncertain prognosis"],ans:2},
{q:"'Resistenzlage' means?",opts:["patient resistance","antibiotic resistance pattern","drug level","dosage"],ans:1},
{q:"'Kurative Therapie nicht möglich' means?",opts:["Curative therapy possible","Curative started","Curative therapy not possible","Curative completed"],ans:2},
{q:"'Sowohl...als auch' means?",opts:["neither...nor","either...or","both...and","not only...but also"],ans:2},
{q:"'Einwilligungsfähigkeit' means?",opts:["physical ability","decision-making capacity","medical history","insurance status"],ans:1},
{q:"'Behandlungspflicht' means?",opts:["right to refuse","duty to treat","optional treatment","emergency only"],ans:1},
{q:"'Prognose quoad vitam infaust' means?",opts:["Very good life prognosis","Uncertain prognosis","Poor life prognosis","Excellent prognosis"],ans:2},
{q:"'Leitliniengerecht behandeln' means?",opts:["Treat against guidelines","Treat according to guidelines","Treat experimentally","Treat traditionally"],ans:1},
{q:"'Die Aufklärungspflicht' means?",opts:["right to privacy","duty to inform patients","duty to document","duty to treat"],ans:1},
{q:"'Klinisches Bild ist komplex' means?",opts:["Simple clinical picture","Improving clinical picture","Complex clinical picture","Clear clinical picture"],ans:2},
{q:"'Rezidiv' means?",opts:["first occurrence","improvement","recurrence/relapse","remission"],ans:2},
{q:"'Remission' means?",opts:["relapse","worsening","recurrence","remission/symptom reduction"],ans:3},
{q:"'Hospitalisierung notwendig' means?",opts:["Hospitalization optional","Hospitalization not needed","Hospitalization necessary","Hospitalization risky"],ans:2},
{q:"'Die Anamnese erheben' means?",opts:["Document diagnosis","Take medical history","Write care plan","Give medication"],ans:1},
{q:"'Maßnahme ist verhältnismäßig' means?",opts:["Measure excessive","Measure proportionate","Measure insufficient","Measure unnecessary"],ans:1},
{q:"'Ich würde eine Konsultation empfehlen' — mood?",opts:["Indikativ","Imperativ","Konjunktiv II","Konjunktiv I"],ans:2},
{q:"'Unter Vorbehalt' means?",opts:["unconditionally","with reservation/subject to change","immediately","permanently"],ans:1},
{q:"'Die Schweigepflicht' means?",opts:["duty to speak","professional confidentiality","duty to document","duty to report"],ans:1},
{q:"'Postoperative Komplikation' means?",opts:["Pre-operative risk","Post-operative complication","Intraoperative finding","Anaesthetic effect"],ans:1},
{q:"'Interdisziplinäre Fallkonferenz' means?",opts:["Single-specialty meeting","Family meeting","Interdisciplinary case conference","Team training"],ans:2},
{q:"'Die Therapieoptionen abwägen' means?",opts:["Ignore therapy options","Apply therapy immediately","Weigh up therapy options","Document therapy only"],ans:2},
{q:"'Infaust' means?",opts:["favorable prognosis","uncertain prognosis","unfavorable/hopeless prognosis","improving prognosis"],ans:2},
{q:"'Wenngleich die Prognose ungünstig ist' starts a?",opts:["causal clause","concessive clause","temporal clause","conditional clause"],ans:1},
{q:"'Symptomkonstellation' means?",opts:["one symptom","symptom pattern/constellation","symptom treatment","symptom history"],ans:1},
{q:"'Chronifizierung vermeiden' means?",opts:["Promote chronification","Accept chronification","Avoid chronification","Document chronification"],ans:2},
{q:"'Palliativmedizin' means?",opts:["Emergency medicine","Palliative medicine","Preventive medicine","Rehabilitation medicine"],ans:1},
{q:"'Zeitkritische Intervention' means?",opts:["Optional intervention","Time-sensitive/urgent intervention","Future intervention","Minor intervention"],ans:1},
{q:"'Sterbehilfe' is?",opts:["birth assistance","surgery assistance","assisted dying/euthanasia","emergency assistance"],ans:2},
{q:"'Die Rekonvaleszenz' means?",opts:["relapse","surgery","convalescence/recovery period","diagnosis"],ans:2},
{q:"'Qualitätssicherung' means?",opts:["quality reduction","quality assurance","quality research","quality control only"],ans:1},
{q:"'Unter strenger Indikationsstellung' means?",opts:["With broad indications","Under strict indication criteria","Without indications","Against indications"],ans:1},
{q:"'Patientenautonomie respektieren' means?",opts:["Override patient wishes","Respect patient autonomy","Ignore patient wishes","Document patient wishes"],ans:1},
{q:"'Angesichts der Komplexität' means?",opts:["Despite complexity","Before complexity","In view of the complexity","After complexity"],ans:2},
{q:"'Die Mortalität' means?",opts:["morbidity rate","mortality rate","recovery rate","infection rate"],ans:1},
{q:"'Langzeittherapie' means?",opts:["short-term therapy","emergency therapy","long-term therapy","one-time therapy"],ans:2},
{q:"'Die Multiresistenz' means?",opts:["single resistance","multi-drug resistance","no resistance","partial resistance"],ans:1},
{q:"'Unter engmaschiger Kontrolle' means?",opts:["Under loose supervision","Under close monitoring","Without monitoring","Under monthly check"],ans:1},
{q:"'Informed Consent' auf Deutsch ist?",opts:["Patientenverfügung","informierte Einwilligung","Schweigepflicht","Behandlungspflicht"],ans:1},
{q:"'Stationäre Behandlung vs. ambulante Behandlung' means?",opts:["Surgery vs medicine","Inpatient vs outpatient","Emergency vs routine","Morning vs evening"],ans:1},
{q:"'Prognostisch ungünstig' means?",opts:["Good prognosis","Uncertain prognosis","Unfavorable prognosis","Improving prognosis"],ans:2},
{q:"'Risiko-Nutzen-Abwägung' means?",opts:["Treatment plan","Risk-benefit assessment","Patient consent","Clinical guideline"],ans:1},
{q:"'Therapieadhärenz' means?",opts:["therapy cost","therapy adherence/compliance","therapy result","therapy duration"],ans:1},
{q:"'Die Befundlage erfordert weitere Diagnostik' means?",opts:["Findings are clear","Findings require further testing","Findings are normal","Findings are documented"],ans:1},
{q:"'Komorbidität' means?",opts:["main diagnosis","co-existing condition / comorbidity","treatment complication","medication side effect"],ans:1},
{q:"'leitliniengerecht behandeln' means?",opts:["Treat experimentally","Treat according to guidelines","Treat with new methods","Treat conservatively"],ans:1},
{q:"'Die Einwilligungsfähigkeit prüfen' means?",opts:["Check consent form","Assess capacity to consent","Obtain signature","Call family"],ans:1},
{q:"'patientenzentrierte Versorgung' means?",opts:["Cost-focused care","Doctor-led care","Patient-centred care","Efficiency-focused care"],ans:2},
{q:"'nosokomiale Infektion' means?",opts:["community infection","hospital-acquired infection","chronic infection","viral infection"],ans:1},
{q:"'interdisziplinäre Fallkonferenz' means?",opts:["Single doctor review","Interdisciplinary case conference","Patient interview","Nurse handover"],ans:1},
{q:"'Die Prognose ist verhalten optimistisch' means?",opts:["Prognosis is very good","Prognosis is poor","Prognosis is cautiously optimistic","Prognosis is unknown"],ans:2},
],
}

export const PB=[
{id:'p1',lv:'A1',q:"'Guten Morgen' means?",opts:["Good night","Good morning","Good evening","Goodbye"],ans:1},
{id:'p2',lv:'A1',q:"Article for 'Krankenhaus'?",opts:["der","die","das","den"],ans:2},
{id:'p3',lv:'A1',q:"'Ich ___ Krankenschwester.'",opts:["bin","bist","ist","sind"],ans:0},
{id:'p4',lv:'A1',q:"'Bitte' means?",opts:["Thank you","Sorry","Please","Goodbye"],ans:2},
{id:'p5',lv:'A1',q:"'Wie geht es Ihnen?' means?",opts:["Where are you?","How are you?","Who are you?","What do you want?"],ans:1},
{id:'p6',lv:'A1',q:"German for 'nurse' (female)?",opts:["Arzt","Patient","Krankenschwester","Rezeptionist"],ans:2},
{id:'p7',lv:'A1',q:"'Das Bett' means?",opts:["chair","table","bed","door"],ans:2},
{id:'p8',lv:'A1',q:"'Die Hand' means?",opts:["foot","hand","head","arm"],ans:1},
{id:'p9',lv:'A1',q:"'Danke' means?",opts:["Please","Sorry","Hello","Thank you"],ans:3},
{id:'p10',lv:'A1',q:"'Montag' is?",opts:["Sunday","Monday","Tuesday","Wednesday"],ans:1},
{id:'p11',lv:'A1',q:"'Wo ist die Toilette?' means?",opts:["When?","Who?","Where is toilet?","What time?"],ans:2},
{id:'p12',lv:'A1',q:"'Der Arzt' means?",opts:["nurse","patient","doctor","hospital"],ans:2},
{id:'p13',lv:'A2',q:"Correct word order?",opts:["Ich gehe heute ins Krankenhaus","Heute ich gehe","Ins Krankenhaus ich heute gehe","Ich heute gehe"],ans:0},
{id:'p14',lv:'A2',q:"Verb form: 'sie (she) arbeit___'?",opts:["arbeite","arbeitest","arbeitet","arbeiten"],ans:2},
{id:'p15',lv:'A2',q:"'Haben Sie Schmerzen?' means?",opts:["Have insurance?","Are you in pain?","Have medicine?","Are you a doctor?"],ans:1},
{id:'p16',lv:'A2',q:"'Zweimal täglich' means?",opts:["once daily","twice daily","three times daily","weekly"],ans:1},
{id:'p17',lv:'A2',q:"'nüchtern bleiben' means?",opts:["must rest","stay fasting","must drink","must exercise"],ans:1},
{id:'p18',lv:'A2',q:"'Blutdruck ist erhöht' means?",opts:["BP low","BP normal","BP elevated","BP dangerous"],ans:2},
{id:'p19',lv:'A2',q:"'schwindelig' means?",opts:["painful","sleepy","dizzy","nauseous"],ans:2},
{id:'p20',lv:'A2',q:"'Die Infusion' is?",opts:["tablet","injection","IV drip","bandage"],ans:2},
{id:'p21',lv:'A2',q:"'Stationär aufgenommen' means?",opts:["Outpatient","Inpatient admitted","Discharged","Emergency"],ans:1},
{id:'p22',lv:'A2',q:"'Die Übergabe' means?",opts:["admission","surgery","handover","discharge"],ans:2},
{id:'p23',lv:'A2',q:"'Bitte unterschreiben Sie' means?",opts:["Wait","Sign here","Sit","Read this"],ans:1},
{id:'p24',lv:'A2',q:"'Das Rezept' means?",opts:["appointment","prescription","report","result"],ans:1},
{id:'p25',lv:'A2',q:"'Kann ich Ihnen helfen?' means?",opts:["Can I help?","Can you help?","Do I need help?","Do you need?"],ans:0},
{id:'p26',lv:'B1',q:"Perfekt: 'Arzt ___ Diagnose ___ (stellen)'?",opts:["hat...gestellt","ist...gestellt","hat...stellte","hatte...gestellt"],ans:0},
{id:'p27',lv:'B1',q:"'obwohl' means?",opts:["because","if","although","so that"],ans:2},
{id:'p28',lv:'B1',q:"'sobald' means?",opts:["although","as soon as","before","after"],ans:1},
{id:'p29',lv:'B1',q:"'Mobilisation steigern' means?",opts:["stopped","gradually increase mobilization","already happened","not needed"],ans:1},
{id:'p30',lv:'B1',q:"'Schmerzen strahlen in Arm' means?",opts:["Right arm pain","Pain radiates to arm","Chest pain","Leg pain"],ans:1},
{id:'p31',lv:'B1',q:"'falls' means?",opts:["because","although","if","when"],ans:2},
{id:'p32',lv:'B1',q:"'Labore noch ausstehend' means?",opts:["Results ready","Results pending","Results normal","Results negative"],ans:1},
{id:'p33',lv:'B1',q:"Modal for obligation: 'Patient ___ nüchtern sein'?",opts:["kann","darf","muss","soll"],ans:2},
{id:'p34',lv:'B1',q:"'Übergabe um 14 Uhr' — what at 14:00?",opts:["Procedure","Shift handover","Admission","Family meeting"],ans:1},
{id:'p35',lv:'B1',q:"'weil' introduces?",opts:["condition","reason/cause","contrast","result"],ans:1},
{id:'p36',lv:'B1',q:"'damit' introduces?",opts:["concessive","purpose","causal","conditional"],ans:1},
{id:'p37',lv:'B1',q:"'Dekubitus dokumentieren' means?",opts:["Treat surgically","Document pressure sore","Heal wound","Needs surgery"],ans:1},
{id:'p38',lv:'B2',q:"'Symptomatik unspezifisch' means?",opts:["Clear symptoms","Non-specific symptoms","Severe symptoms","Improving"],ans:1},
{id:'p39',lv:'B2',q:"Konjunktiv II: 'früher behandelt worden ___'?",opts:["wurde","worden wäre","war","würde"],ans:1},
{id:'p40',lv:'B2',q:"'Compliance eingeschränkt' means?",opts:["Fully compliant","Limited compliance","Cooperative","Questions everything"],ans:1},
{id:'p41',lv:'B2',q:"'Angesichts der Schwere' means?",opts:["After the severity","Before severity","In view of the severity","Despite severity"],ans:2},
{id:'p42',lv:'B2',q:"'Maßnahme ineffektiv erwiesen' means?",opts:["Effective","Ineffective","Not tried","Needs time"],ans:1},
{id:'p43',lv:'B2',q:"'indiziert' means?",opts:["contraindicated","indicated/appropriate","optional","dangerous"],ans:1},
{id:'p44',lv:'B2',q:"'Laborwerte deuten auf Anämie' means?",opts:["Exclude anemia","Confirm anemia","Suggest/indicate anemia","Normal values"],ans:2},
{id:'p45',lv:'B2',q:"'Schweigepflicht wahren' means?",opts:["Share patient info freely","Maintain confidentiality","Document everything","Report to family"],ans:1},
{id:'p46',lv:'B2',q:"'evidenzbasiert' means?",opts:["traditional","evidence-based","experimental","optional"],ans:1},
{id:'p47',lv:'B2',q:"'Ätiologie unklar' means?",opts:["Cause clear","Cause unknown","Treatment known","Prognosis good"],ans:1},
{id:'p48',lv:'B2',q:"'Es steht außer Frage' means?",opts:["Questionable","Without doubt / unquestionable","Hypothetical","Conditional"],ans:1},
]

export function pickPlacementQs(){
  const byLv={A1:[],A2:[],B1:[],B2:[]}
  PB.forEach(q=>byLv[q.lv].push(q))
  const pick=(arr,n)=>[...arr].sort(()=>Math.random()-.5).slice(0,n)
  return [...pick(byLv.A1,4),...pick(byLv.A2,4),...pick(byLv.B1,4),...pick(byLv.B2,3)]
}

export function pickExercises(level){
  const bank=EXERCISES[level]||EXERCISES.A1
  return [...bank].sort(()=>Math.random()-.5).slice(0,20)
}
